### ISSUE TITLE
Adicionar a API a diferenca de horario em relacao a brasilia (temos 4 fusos horários). E a possibilidade de alertas para a mudancas de horario de verao/inverno para um CEP. 

### ISSUE THREAD

**Issue by ThomasGl** [BrasilAPI/BrasilAPI#106]
Ja estagiei numa empresa que precisava desesperadamente mexer todo o banco de dados para se adaptar a esses problemas, me parace algo bem simples e muito importante para alguns a sua implementacao. Me parece ter diversas solucoes possiveis.

**Comment by dordetto** [comment]
Fiquei curioso em que o horário tem relação com o CEP. Como disse que estagiou em empresa e que isso era importante, fiquei muito curioso em saber como o fuso horário afeta a consulta de CEP.
