### ISSUE TITLE
Criei um Projects aqui no Github com o Roadmap

### ISSUE THREAD

**Issue by filipedeschamps** [BrasilAPI/BrasilAPI#110]
Agora que consegui reestabilizar a agenda de vídeos do canal, estou voltando aqui para o projeto e o objetivo é levar até a versão 1.0 👍 

https://github.com/filipedeschamps/BrasilAPI/projects/1

Eu vou ter que atropelar algumas decisões para acelerar o desenvolvimento, e talvez uma ideia justa é deixar ele na versão 0.9 e depois disso com a avaliação da comunidade decidir como levar ele para a versão 1.0, inclusive como transferir o BrasilAPI para uma Org 🤝

**Comment by daniloster** [comment]
Infelizmente não tenho acesso para ajudar nos tickets. Um deles é sobre tratamento de error que é parte da sugestão iniciada com este PR: https://github.com/filipedeschamps/BrasilAPI/pull/115

De que outra forma posso ajudar?

**Comment by RodriAndreotti** [comment]
@filipedeschamps No momento estou sem tempo para ajudar desenvolvimento, mas posso disponibilizar meu server para hospedar a API em um .org sem custo, não é um server muito parrudo, mas para iniciar acho que dá para quebrar um galho, só preciso saber quais os requisitos de servidor para ver se preciso adaptar algo.

**Comment by lucianopf** [comment]
Boa mestre @filipedeschamps !!

Estou fechando a issue pra organizar um pouco as que ainda apresentam pendências 😬 🚀
