### ISSUE TITLE
Endpoint para feriados

### ISSUE THREAD

**Issue by marcioeric** [BrasilAPI/BrasilAPI#118]
Olá amigos!

Fiquei conhecendo o projeto pelo @filipedeschamps e fiquei curioso.

Dando uma olhada, o que vocês acham de um endpoint para feriados?

Mostrando os nacionais e municipais?

**Comment by barbosamaatheus** [comment]
Criei um pull request para isso :)

**Comment by barbosamaatheus** [comment]
Acebei de ver que essa issue está duplicada com a #68.

**Comment by lucianopf** [comment]
A ideia é excelente!! 🚀 

Eu tinha um plano de quando sobrasse um tempinho desenvolver essa rota tbm mas tava pensando em seguir usando algo tipo https://github.com/pagarme/business-moment 😬 

Já ouviram falar dessa libzinha?

**Comment by barbosamaatheus** [comment]
Ainda não conhecia... vou tentar dar uma olhada, parece promissor.

Além da minha solução(Está linkada nessa issue), tivemos também a solução do @gustavobordinho em: https://github.com/BrasilAPI/BrasilAPI/pull/161

**Comment by barbosamaatheus** [comment]
@lucianopf nesse caso, o endpoint receberia uma data e retornaria a informação para aquela data ou seria melhor usar o https://github.com/pagarme/business-calendar para retornar todos os feriados do ano de uma vez só?

**Comment by lucianopf** [comment]
Inicialmente meu plano de implementação era recebendo uma data de base e calculando os próximos dias úteis mas podemos fazer com o business-calendar fazendo uma listagem mais completa 😬  

Obs: confesso que não sei usar só o business-calendar hehehe mas aí é só estudar um pouquinho e acho que da pra desenrolar 😬

**Comment by barbosamaatheus** [comment]
@lucianopf, abri um PR para isso. Vê se era mais ou menos isso que você queria... posso fazer alguns ajustes se precisar :)

**Comment by murilohns** [comment]
fechado pelo #256
