### ISSUE TITLE
Package manager 

### ISSUE THREAD

**Issue by Nikolassantos** [BrasilAPI/BrasilAPI#123]
Entrei no projeto a alguns dias e senti muito a falta de um aviso na documentação falando sobre qual package manager usar, acho que seria muito valido criar uma padronização entre as pessoas que estão contribuindo.

**Comment by lucianopf** [comment]
Bom ponto @Nikolassantos !

De fato não há em nenhum lugar explicando o package manager explicitamente 😢 
Dando uma olhadinha no guia de contribuição (https://github.com/BrasilAPI/BrasilAPI/blob/master/CONTRIBUTING.md#iniciando) percebi que lá ele usa exclusivamente o NPM e olhando o projeto hoje só existe `package-lock.json` que é resultado do uso do NPM e não existe 
nenhum `yarn.lock` que indica que o NPM é provavelmente o package manager oficial do projeto.

Acho que sua dúvida faz total sentido, topa propor uma melhoria na documentação pra indicar o NPM como package manager oficial? 🙏 😬

**Comment by Nikolassantos** [comment]
> que o NPM é provavelmente o package manager oficial do projeto.
  

@lucianopf Claro, talvez um paragrafo na documentação explicando o Packager Manager seria o bastante?

**Comment by Nikolassantos** [comment]
@lucianopf abri uma PR com as modificações pedidas acima :https://github.com/BrasilAPI/BrasilAPI/pull/188
