### ISSUE TITLE
Bug: Rota DDD não funciona retorna "DDD não existe" para DDDs válidos.

### ISSUE THREAD

**Issue by AugustoResende** [BrasilAPI/BrasilAPI#128]
Causa:

cidades-promise está tentando chamar a api http://ddd.pricez.com.br/ que está fora do ar. É necessário substituir ou acrescentar provedores de backup para esta informação.

Reproduzir:
npm run dev
Chame o endpoint ```http://localhost:3000/api/ddd/v1/11```
Ele retorna ```{"error":"DDD não existe."}``` mesmo sendo um DDD válido.

**Comment by AugustoResende** [comment]
Fonte 'oficial' da informação: https://dados.gov.br/dataset/codigos-nacionais-cn

**Comment by AugustoResende** [comment]
Outra: https://www.anatel.gov.br/hotsites/CodigosNacionaisLocalidade/codigos_uf/codigos_<sigla do estado>.pdf

**Comment by nandumoura** [comment]
esse

> Causa:
> 
> cidades-promise está tentando chamar a api http://ddd.pricez.com.br/ que está fora do ar. É necessário substituir ou acrescentar provedores de backup para esta informação.
> 
> Reproduzir:
> npm run dev
> Chame o endpoint `http://localhost:3000/api/ddd/v1/11`
> Ele retorna `{"error":"DDD não existe."}` mesmo sendo um DDD válido.

esse endpoint acho que não funciona

**Comment by RodriAndreotti** [comment]
Eu acho que esse endpoint foi usado como teste pelo rapaz que desenvolveu o módulo de ddd, e depois ele acabou deixando de lado.

**Comment by omurilo** [comment]
> Eu acho que esse endpoint foi usado como teste pelo rapaz que desenvolveu o módulo de ddd, e depois ele acabou deixando de lado.

Na verdade não, é uma api que por muito tempo (até esses dias) funcionava muito bem, com dados coesos e tudo, porém, não sei o motivo ela está offline realmente.

Inclusive fornecia várias outras informações, exemplo:

[Reportagem do canal tech](https://canaltech.com.br/apps/pricez-descubra-qual-o-plano-de-celular-ideal-para-voce/)
[Histórico do Wayback Machine](https://web.archive.org/web/20200216112553/http://ddd.pricez.com.br/)

**Comment by lucianopf** [comment]
Poxa 😢 

Menos uma fonte de dados legal, essa do DDD era bem interessante =(

Curti bastante que vcs já encontraram diversas outras opções de fonte de dados! 😱 ❤️ 

Vcs sabem dizer se já tem alguém atuando nessa issue? 😬

**Comment by localhostloco** [comment]
Eu dei uma olhada e parece ser que tem um timeout no `cidades-promise`. O domínio que ele usa como fonte é "ddd.pricez.com.br", fazendo a consulta manualmente eu tenho um timeout vindo do servidor, mas o ping resolveu a IP então pode ser que eles tenham problemas técnicos ou migraram a API ou sei lá 😢

**Comment by matheuslcandido** [comment]
Fala pessoal, como vai?

Estou trabalhando nessa issue seguindo o .csv do https://dados.gov.br/dataset/codigos-nacionais-cn passado pelo @AugustoResende.

De início eu procurei formas alternativas para ler o .csv e retornar os dados, porém, analisando melhor o código atual eu reparei que o end point `https://brasilapi.com.br/api/banks/v1/` já tinha uma lógica fazendo exatamente o que precisava ser feito, sendo assim, decidi implementar seguindo o mesmo modelo que já existe no projeto.

Também pensei em formas de adicionar serviços de fallback, mas, para liberar a solução o mais breve possível e voltar com o funcionamento da requisição, acho que podemos deixar essas questões para outra issue? o que vocês acham?

Estou finalizando a implementação dos testes e da documentação e logo realizo o commit para solicitar o review e discutirmos sobre como ficou.

**Comment by lucianopf** [comment]
Uhuuul que massa @matheuslcandido ! 🤩 

Se precisar de ajuda com algo é só chamar! 😬 🙏
