### ISSUE TITLE
API de georeferenciamento de locais

### ISSUE THREAD

**Issue by victor-lby** [BrasilAPI/BrasilAPI#139]
A ideia desse domain é utilizar versões gratuitas de diversas ferramentas de georreferenciamento: TomTom, MapBox, Google Maps, Facebook Places, Foursquare, entre outros que têm versões gratuitas embora limitadas.

O usuário da API passa uma localização XX.XXXX, YY.YYYY e um raio R, e a API retorna todos os places dentro das APIs disponíveis, armazenando a resposta em cache persistente até que a resposta mude.

Possíveis endpoints dentro desse domain:
```
GET: /places/v1/lat/XX/long/YY/radius/R/
Return
 - { name: "Place Name", description: "Descrição do local", placeType: "Restaurant", image: "https://...." }
```

As coordenadas teriam de ser, obrigatoriamente, em território brasileiro.

O que vocês acham? Quero começar a contribuir com a comunidade, sou programador PHP a 12 anos, venho estudando Node a uns anos e arrumei uma vaga em uma empresa grande recentemente, quero trabalhar em conjunto com a comunidade para me aprimorar tecnicamente e entender melhor da linguagem.

Aguardo feedbacks da ideia 🇧🇷

**Comment by marlonbrito** [comment]
Achei muito boa essa ideia! parabéns aguardo o seu Pull Request!

**Comment by victor-lby** [comment]
O problema dessa endpoit é a performance, como performar diversas consultas de forma a não gargalar o servidor? Pensei em algo usando Promises.all(), e chamando todas as APIs ao mesmo tempo, de forma async - sem await - com um timeout bem pequeno - 200ms. A API retornar, retornou, a que não retornar, paciência, retorna objeto vazio para aquele request.

É um MUST para essa API ter um limite de requisições por IP, e que caso alguma das APIs de consulta chegue no limite mensal/diário, pare de consultar nela até virar o período dos créditos. 

Ainda estou pensando se essa é uma ideia válida e oportuna para o BrasilAPI.

**Comment by italods** [comment]
Essa ideia é muiiiiiito boa! 
Precisei de algo parecido com isso recentemente e não encontrei nada.
Ansioso para ver o progresso dessa ideia.

**Comment by victor-lby** [comment]
Aguardando esse [PR-133](https://github.com/BrasilAPI/BrasilAPI/pull/133) subir pra implementar

**Comment by victor-lby** [comment]
Vou fazer baseado no PR #133
