### ISSUE TITLE
Código de barras de produtos

### ISSUE THREAD

**Issue by JoaoEymard** [BrasilAPI/BrasilAPI#146]
Seria interessante termos na API uma rota para produtos. Identificar os produtos através do código de barras.

Isso poderia ser atendido de duas formas:
- Coletar informações de locais públicos;
- Os sistemas informariam para a API quando tivesse um produto novo;

**Comment by arrudagates** [comment]
Fiz uma pesquisa sobre isto e encontrei que a GS1 possue API's de consulta de produtos no Cadastro Nacional de Produtos
[API](https://www.gs1br.org/servicos-e-solucoes/api)
[Manual da API](https://www.gs1br.org/educacao-e-pratica/Documents/Modelo%20para%20Materiais%20T%C3%A9cnicos%20CRM.pdf)

**Comment by JoaoEymard** [comment]
Isso mesmo! Obrigado
