### ISSUE TITLE
Buscar CEP pelo logradouro

### ISSUE THREAD

**Issue by edysegura** [BrasilAPI/BrasilAPI#15]
Olá!

Parabéns pela iniciativa!! Gostaria de sugerir um endpoint para retornar os possíveis CEP informando um logradouro.

![image](https://user-images.githubusercontent.com/5324414/74394413-55c74f00-4deb-11ea-984b-bd97405acd96.png)

![image](https://user-images.githubusercontent.com/5324414/74394454-68da1f00-4deb-11ea-9c71-2920eec71bba.png)

**Comment by OtavioCapila** [comment]
Abre um PR aqui -> [cep-promise](https://github.com/filipedeschamps/cep-promise).
Como pode ser visto [aqui](https://github.com/filipedeschamps/cep-promise/blob/6dd80a3fd839ccbf3f11c51f87125d105103d5e0/src/services/correios.js#L10) a pesquisa está sendo feita somente com o CEP.

**Comment by filipedeschamps** [comment]
Ah que show!!!! E agora ótima questão: isso primeiro deveria ser implementado em um endpoint separado no BrasilAPI, com cache e tudo mais, e depois utilizado no cep-promise ou outra lib, correto?
