### ISSUE TITLE
[São Paulo | REMOTO – Analista de Segurança (RedTeam) na GC Security] #vagasbyintera

### ISSUE THREAD

**Issue by rafaelafrazao** [BrasilAPI/BrasilAPI#152]
A GC Security nasceu em 2008 e, desde então, trabalha incansavelmente para gerenciar os riscos digitais de companhias de todos os portes e setores de mercado, garantindo visibilidade total sobre vulnerabilidades e falhas de segurança para proteger ativos, dados, aplicações e sistemas.

Estamos em busca de talentos que topem o desafio de ser Analista de Segurança (RedTeam)!
As principais responsabilidades do RedTeam são: realizar a avaliação de segurança em aplicações WEB, aplicativos mobile e infraestrutura (redes e servidores), atender a clientes com alto nível de segurança utilizando skills para by-pass em WAF e Firewall e gerar evidências e descrição das vulnerabilidades encontradas.

O que você precisa para vir com a gente nesse desafio? Ter experiência comprovada em ferramentas de Pentest como Burp, Frida, Nmap, Sqlmap, Nuclei, Amass e outras, bem como ter conhecimentos sólidos em Linux, programação/script e frameworks de segurança de dados, como PCI, OWASP TOP 10, NIST E ISSO 27001. Além de um nível de ética muito alto, ser colaborativo, autogerenciamento, ser uma pessoa analítica e com muito foco!

Será considerado um diferencial: ter conhecimento em Code Review, OSINT e Forense Digital.

Faz sentido pra você? Conhece alguém que se encaixe no desafio?
É só se inscrever pelo link: https://bit.ly/370Egga

#oportunidade #linux #pentest #pentester #securityanalyst

**Comment by enieber** [comment]
@rafaelafrazao por favor postar vaga em grupos como [vagas-backend-br](https://github.com/backend-br/vagas) e [vagas-frontend-br](https://github.com/frontendbr/vagas) abrir issues apenas para coisas relacionadas ao projeto. 

Obrigado pela compreensão.
