### ISSUE TITLE
Busca de profissionais por número de conselho

### ISSUE THREAD

**Issue by gustavofabro** [BrasilAPI/BrasilAPI#155]
Olá pessoal, estive pensando em uma API que retorna dados de um profissional através da consulta do seu número de conselho, como o CRM (médicos), CREA (engenheiros), e por aí vai. 

Encontrei uma API que retorna essas informações: https://www.consultacrm.com.br/index/api. Ela possui alguns domínios específicos para cada tipo de conselho, por exemplo tem o https://www.consultaoab.com.br/index/api para consulta de registros da OAB. Mas na verdade basta trocar o tipo de conselho no parâmetro da API que vai funcionar, mesmo tu estando no domínio de outro conselho:

https://www.consultacrm.com.br/api/index.php?tipo=crea&uf=&q=Joao&chave=CHAVE&destino=json 

O problema é que ele é limitada a 100 consultas mensais no plano gratuito, mas isso poderíamos resolver com o cache das informações, imagino que dê de fazer um trabalho bem legal nesse sentido, realizando consultas diárias, e persistindo esses resultados para reutilizar em outras consultas.

Minha ideia seria criar uma API para cada conselho. Não manjo muito do Next mas me disponho a desenvolver também.

O que acham da ideia? Alguém conhece alguma outra API que retorna esse tipo de informação?

**Comment by rodbv** [comment]
Fala Gustavo! Excelente ideia, consulta de registros profissionais é muito útil.

Algumas considerações:

- É preciso ver se fazer cache local do consultacrm.com.br não infringiria os termos e condições de "fair use"  da API deles, visto que eles são um serviço comercial. Uma outra questão é que se fossemos criar um cache disso, teria que ver onde seriam armazenados esses dados, e como seria arcado esses custos de armazenamento.

- Pro caso do registro na OAB, eu acho que existe uma alternativa aberta em https://cna.oab.org.br, pelo que vi eles tem um endpoint em `https://cna.oab.org.br/Home/Search` que permite chamadas POST para pesquisa. O que poderia ser feito aqui no BrasilAPI seria criar uma fachada mais amigável para essa API? Mais ou menos como foi feito pro CEP.

**Comment by gustavofabro** [comment]
Massa @rodbv! Por acaso você se dispõe a ajudar no desenvolvimento? Se sim, poderíamos nos organizar para ir atrás dessas informações que você comentou e botar a mão na massa.
