### ISSUE TITLE
Testes não estão rodando no Github

### ISSUE THREAD

**Issue by gustavobordinho** [BrasilAPI/BrasilAPI#162]
Após fazer o fork e dar push nas alterações, os testes não estão funcionando na aba de PR.

O status permanece nesse:
`e2e-tests Expected — Waiting for status to be reported`

Ao rodar **`yarn test`**, o teste escrito passa normalmente.

**Comment by paulo-santana** [comment]
Isso é um problema que está nos importunando desde que o workflow foi criado. Por algum motivo que desconhecemos, o Github Actions não está conseguindo rodar o workflow quando quem dispara o `deployment_status` é um fork. Ele só funciona quando é feito um PR entre duas branches diferentes do mesmo repositório.

O Luciano começou a investigar no PR #107, mas o projeto começou a receber tanta contribuição que isso acabou tendo que esperar.

No fim, o Deschamps decidiu a forma que ele iria gerenciar os PRs seria a seguinte:

- Se você enviou um PR para a master dele, ele redirecionaria esse PR pra uma branch intermediária, por exemplo, uma chamada pr-target.
- Ele aceitaria esse PR da sua branch para a pr-target, e então faria um PR interno da pr-target pra master, e com isso o workflow seria executado normalmente.

**Comment by dsmello** [comment]
@lucianopf , eu estava revendo o erro e acho o problema está no lado da Vercel, quando o bot deles faz a requisição ao github está passando o parametro 'repository' de onde o bot está instalado e não da origem do commit. Se desse para falar com eles.

[GITHUB actions - deployment_status](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#deployment_status)

**Comment by lucianopf** [comment]
Isso mesmo @gustavobordinho e @paulo-santana é um problema conhecido 😭 

Como foi comentado o @filipedeschamps optou por fazer um processo mais manual pra resolução da restrição.
Como acredito que faz sentido o comportamento da Vercel acho que faz mais sentido a gnt mudar um pouco a abordagem dos testes e abri esse PR que muda um pouquinho o comportamento https://github.com/BrasilAPI/BrasilAPI/pull/168 😬 

Testei abrindo um PR no repo original e no fork e ambos deram certo então acho que faz sentido seguir assim pra ao menos desbloquear os diversos PRs agarrados, o que acham? 🙏 😬

**Comment by gustavobordinho** [comment]
Obrigado pelas respostas!

@lucianopf Assim como mencionado na PR #168, acho totalmente viável seguir com os testes em um servidor local, como você disse, temos muitas PRs agarradas, e colocar em prática o que você descreveu vai satisfazer muitas das issues por aqui e enriquecer o projeto 😃.

**Comment by RodriAndreotti** [comment]
@lucianopf Acho que deu BO de novo na integração da Vercel, parece que o CI/CD não está rodando para fazer o deploy.

**Comment by lucianopf** [comment]
Eiiita, vou olhar aqui! 👀 
Só uma dúvida, o PR ta 100% atualizado com a master? 🙏 😬

**Comment by lucianopf** [comment]
Eiiiita @RodriAndreotti , verdade! 😱 

Tem algum ponto que foi pedido lá na Vercel pra atualizar o cadastro. Já entrei em contato com o @filipedeschamps pra gente liberar isso 🙏 😬

**Comment by lucianopf** [comment]
@RodriAndreotti acredito que consegui consertar, pode tentar um push dnv pfv? 🙏

**Comment by RodriAndreotti** [comment]
@lucianopf feito, rodando os testes

**Comment by lucianopf** [comment]
Uhuull! 🚀 🕺 

Vou fechar essa issue pra ir organizando as issues abertas! 😬

Muito obrigado @RodriAndreotti , se tiver qualquer problema pfv é só avisar! ^^
