### ISSUE TITLE
API CNPJ

### ISSUE THREAD

**Issue by RuanNunes** [BrasilAPI/BrasilAPI#164]
hello, desenvolvi um projeto para tratar de cnpj 
segue link do repo para quem quiser contribuir e quem sabe no futuro adicionar juntamente no repo da organização 
https://github.com/RuanNunes/find-cnpj

**Comment by ruankotovich** [comment]
Eita, isso é bem interessante, não tenho certeza absoluta mas posso chutar fortemente que isso seria muuuuuuuito utilizado :open_mouth: 

Sobre o seu projeto, os dados são armazenados estaticamente em um banco de dados do próprio projeto ou são utilizados serviços de terceiros? Fiquei com bastante vontade de ajudar nesse :stuck_out_tongue_closed_eyes:

**Comment by RuanNunes** [comment]
tem um script em python que le os csv da receita federal e faz um import inicial em um banco mongodb.
https://github.com/RuanNunes/find-cnpj/tree/master/migrate-cnpj

**Comment by danielboso** [comment]
Dá pra usar pra puxar o cnpj das empresas da bolsa pra questões de declaração de imposto de renda por exemplo. Interessante.

**Comment by KoenomatachiSan** [comment]
Essa API já está em algum lugar? Ou não tem servidor ainda e/ou não pretende ter?

**Comment by RuanNunes** [comment]
ainda não esta hospedada.
