### ISSUE TITLE
API Bancos

### ISSUE THREAD

**Issue by marlonemmerich** [BrasilAPI/BrasilAPI#165]
Olá, pessoal! 

Existe a intenção de implementar algo relacionado a bancos? Por exemplo, uma listagem contendo Nome e código dos bancos, outra API buscando mais dados, etc.
Vi que existe um PR (que foi fechado) que implementaria essa listagem mas não encontrei nenhum outro detalhe.

Um abraço!

**Comment by nandumoura** [comment]
Esse é um dado bem útil

**Comment by Sxigames** [comment]
[eles ainda vão resolver os pull abertos](https://github.com/BrasilAPI/BrasilAPI/projects/1#card-46436456)

**Comment by lucianopf** [comment]
Opa, isso mesmo que o @Sxigames comentou, estamos nos estruturando pra organizar o que ficou pendente 😬 

Mas já adiantando acho que essa API que vc comentou se parece com essa proposta https://github.com/BrasilAPI/BrasilAPI/pull/85 estou certo?

**Comment by marlonemmerich** [comment]
Exatamente isso, @lucianopf! Da maneira que foi feito que era o que eu tinha em mente
Muito bom! Fico no aguardo da liberação 

Obrigado!

**Comment by gustavolivrare** [comment]
@lucianopf @marlonemmerich dúvida genuína: acham que faz sentido mantermos essa issue aberta ou podemos fechar e o Marlon acompanha a resolução através do PR? 😊

**Comment by lucianopf** [comment]
Acredito que podemos fechar sim! 🚀 

Fica a vontade de reabrir se achar necessário @marlonemmerich 😬
