### ISSUE TITLE
Adicionar Resolvers de Bank no grapqhl

### ISSUE THREAD

**Issue by MarconWillian** [BrasilAPI/BrasilAPI#177]
Estou em busca de uma forma de pegar apenas os dados que preciso, não só do endpoint bank, mas tbm dos futuros endpoints de cidade e de estados, assim, estou tentando colocar em dia a funcionalidades ali dentro do GraphQL, eu já criei a parte de banks, e bank com filtro pelo code, mas ainda estou trabalhando, ainda não fiz os testes hehehe, mas em breve já atualizo o PR.

Desculpa se fui precipitado, estou animado em colaborar com este projeto, sendo que o mesmo é minha primeira colaboração.

**Comment by marconwillian** [comment]
> Estou em busca de uma forma de pegar apenas os dados que preciso, não só do endpoint bank, mas tbm dos futuros endpoints de cidade e de estados, assim, estou tentando colocar em dia a funcionalidades ali dentro do GraphQL, eu já criei a parte de banks, e bank com filtro pelo code, mas ainda estou trabalhando, ainda não fiz os testes hehehe, mas em breve já atualizo o PR.
> 
> Desculpa se fui precipitado, estou animado em colaborar com este projeto, sendo que o mesmo é minha primeira colaboração.

PR #178
