### ISSUE TITLE
Aumentar a comunidade

### ISSUE THREAD

**Issue by KoenomatachiSan** [BrasilAPI/BrasilAPI#184]
Gostaria de participar do projeto, vi que havia muitos colaboradores entusiasmados e isso me empolgou. Teria algum canal relacionado ao projeto?

O que acham de criar uma organização para criação de mais projetos open-source?

Melhorar a visão internacional do Brasil sobre tecnologia seria ideal, e estou disposto a trabalhar com vocês!

**Comment by RodriAndreotti** [comment]
Acho que seria interessante ter um canal no slack para o pessoal que já está colaborando poder se comunicar.
Eu toparia também entrar nessa empreitada, tem muitos benefícios, principalmente por ser uma forma legal de trocar informações com outros programadores, uma ótima ~~desculpa~~ oportunidade para estudar, se envolver com projetos que no cotidiano do trabalho talvez nunca tivesse contato.

Fora que também é um baita diferencial no currículo estar envolvido em projetos desse nível

**Comment by KoenomatachiSan** [comment]
Sim sim! Com quem podemos falar a respeito disto?

**Comment by KoenomatachiSan** [comment]
Poderíamos usar o discord, ou algum outro chat para discussão de ideias. 
Podemos usar o planner e o trello pra organização de projetos, e quem sabe conseguir algum investidor ?

**Comment by RodriAndreotti** [comment]
> 
> 
> Sim sim! Com quem podemos falar a respeito disto?

@filipedeschamps , @lucianopf , Acho que é com vocês :-P

**Comment by KoenomatachiSan** [comment]
Oloco! O grande FD? Que isso, me senti um mero mortal perto desse mito

**Comment by KoenomatachiSan** [comment]
Fico aguardando na expectativa imensa de poder poder participar desse projeto.

**Comment by danielboso** [comment]
Tenho interesse em colaborar com algo relacionado ao mercado financeiro.

**Comment by KoenomatachiSan** [comment]
Nossa seria legal hein, uma API pra monitorar o setor financeiro brasileiro, seria muito top!!!@danielboso

**Comment by danielboso** [comment]
@KoenomatachiSan Algo para pegar dados de empresas da bolsa, cotações também seria legal.

**Comment by KoenomatachiSan** [comment]
Isso, você tem conhecimento em algum tipo de banco de dados que tenha esta disponibiloidade de dados?

**Comment by danielboso** [comment]
No momento não. Até andei pesquisando bastante sobre apis, mas não encontrei nada que fosse interessante. Depois tive que focar as coisas e acabei deixando isso de lado.

**Comment by KoenomatachiSan** [comment]
Conforme for podemos dar uma pesquisada, seria bacana criar uma comunidade open-source forte com vários projetos. As vezes sinto que o brasileiro não sabe trabalhar muito em equipe.
Imagina, se nós formassemos uma equipe com 10 desenvolvedores para ajudar a desenvolver mais essa api do @filipedeschamps , e criassemos outras?
O mercado brasileiro está carente de desenvolvedores e apis open-source que ajudem a comunidade.

**Comment by isaiasvallejos** [comment]
Muito legal a ideia, a galera da Pagar.me que tá tocando o repositório com o @lucianopf já está trocando figurinhas para pensar e dar andamento nisso.

Estamos com alguns empasses entre Slack e Discord, ou talvez até lancemos os dois e vemos no que dá? 

Por favor, fiquem à vontade de continuar essa thread com sugestões e dicas para isso, porque iremos precisar de bastante ajuda para fomentar esses canais!

**Comment by KoenomatachiSan** [comment]
Eu, pessoalmente prefiro o Discord. Além de conseguirmos criar BOTS ( projetinhos também open-source  ) para a comunidade também aprender, conseguiriamos colocar muitas ferramentas e áreas de projetos para o canal.
Fica minha dica!

E @isaiasvallejos , caso possa ajudar de alguma maneira a manter este repositório, me passe alguma task, ou crie algo relacionado ao projeto por gentileza.
Vai ser um prazer ajudar o projeto a se desenvolver.

**Comment by isaiasvallejos** [comment]
@KoenomatachiSan 

Decidimos criar um Slack, agradecemos demais sua ideia por aqui! Bora contribuir e conversar por lá agora! #186 

Nós não temos tasks definidas ainda para o BrasilAPI, porque ainda temos muita coisa para ver de todos os Pull Requests e issues criados até agora, então em geral, fique à vontade para ajudar nisso, implementar novas coisas ou conversar e dar ideias pelo novo canal.

**Comment by KoenomatachiSan** [comment]
Feshow! Vamos que vamos!
