### ISSUE TITLE
Ferramenta para padronizar mensagens de commit

### ISSUE THREAD

**Issue by allangrds** [BrasilAPI/BrasilAPI#199]
Como as mensagens podem acabar variando entre cada um, pensei em usarmos o [Commitzen](https://github.com/commitizen/cz-cli).

![image](https://user-images.githubusercontent.com/4103305/105536008-71f78f80-5cce-11eb-96c2-c43ee87fda91.png).

**Comment by murilohns** [comment]
@allangrds curto a ideia

acho interessante inserir isso no `contributing.md`, que tal?

**Comment by allangrds** [comment]
Pensei em colocar como dependência de desenvolvimento também, @murilohns

**Comment by krascovict** [comment]
Uma sugestão é trabalhar com versões de versionamento padrão dos projetos open source, ex: "1.0.01" (na onde 1 é versão, .0 é versão com release em "aberto" e .01 é a versão do release em desenvolvimento) 

Sugestão 2°: Na parte das definições das versões em release recomendo um "changelogs" (Registro de alterações) e se puder um lista de discussões em txt para os desenvolvedores acompanhar quase em tempo real os progressos da alterações, sugestões da API.

**Comment by PauloGoncalvesBH** [comment]
Pessoal, uma solução que acho boa e que posso abrir um PR em breve é:
- Commitzen no `commit-msg` do husky. Dessa forma ao executar `git commit` vai abrir o commitzen no terminal
- Execução de commit lint em pipeline.

Depois disso, posso fazer implementação que é consequência da de cima:
- Geração automática de changelog e release no github com versionamento autoḿatico ao fazer merge com a `master`(usando [semantic-release](https://github.com/semantic-release/semantic-release))

**Comment by PauloGoncalvesBH** [comment]
@krascovict sobre versionamento de API sugiro abrir uma discussão ou issue para vermos as nuances sobre e deixar essa aqui focada apenas no padrão de commit.

**Comment by allangrds** [comment]
Acabei criando o seguinte PR:
https://github.com/BrasilAPI/BrasilAPI/pull/204
