### ISSUE TITLE
Testes de banks estão quebrando

### ISSUE THREAD

**Issue by allangrds** [BrasilAPI/BrasilAPI#205]
### Contexto
Os testes do arquiv `tests/banks-v1.test.js` tem quebrado. Dando uma olhada, foi visto que o endereço `http://www.bcb.gov.br/pom/spb/estatistica/port/ParticipantesSTRport.csv` tem ficado indisponível algumas vezes, causando um erro na nossa API.

O que acham de termos um JSON como fallback? O problema maior está em pensar em como atualizar esse JSON.

**Comment by lucianopf** [comment]
Boa mestre!! Acho mto boa a ideia de ter esse csv de fallback e a gnt atualiza manualmente eventualmente!
