### ISSUE TITLE
Migrar para TypeScript

### ISSUE THREAD

**Issue by LeonardoRosaa** [BrasilAPI/BrasilAPI#210]
Será que não seria válido fazer essa migração para [Typescript](https://www.typescriptlang.org/)?? Acredito que ajudaria muito no desenvolvimento e escalabilidade.

**Comment by cezarmzz** [comment]
@LeonardoRosaa, basicamente qual seria o problema que o TypeScript iria resolver caso fosse usado na implementação da API?

**Comment by LeonardoRosaa** [comment]
Ajudaria a encontrar possíveis erros no desenvolvimento e na manutenção conforme for crescendo a API.

**Comment by RodriAndreotti** [comment]
Na minha humilde opinião, não consigo ver o typescript como uma algo que vá resolver um problema em concreto neste caso (claro que posso estar muito errado nisso... rs), além de adicionar complexidade ao projeto .

**Comment by LeonardoRosaa** [comment]
Hahaha entendo, eu penso que o TypeScript irá servir para evitar problemas também haha principalmente na hora do desenvolvimento como tinha comentado antes... Mas quais complexidade o TypeScript teria na sua opinião?

**Comment by RodriAndreotti** [comment]
Cara, quando lidamos com o Javascript puro (Sim, eu sei que o typescript tbm é javascript... rs), é mais fácil para quem está começando e quer contribuir, o projeto já usa um framework, que já acrescenta certa curva de aprendizagem, uma bateria de testes automatizads, que também tem sua curva de aprendizagem, adicionar o typescript adicionará também outra curva de aprendizagem, para um projeto onde muita gente que está iniciando no mundo da programação está se aventurando.

Entendo o que você diz sobre evitar problemas futuros, e acho isso importante, mas acho que seria interessante, pelo menos num primeiro instante, ter um manual de contribuição detalhando bem como se espera que a contribuição chegue, orientando sobre as melhores práticas e algumas coisas "pegar" nos reviews dos PR's.

Muitos dos erros os testes automatizados vão capturar, visto que os endpoints são somente leitura e a maioria, basicamente é um bridge entre outra API ou fonte de dados e esta, não temos que nos preocupar tanto com input de dados.

Bom, mas como falei, esta é minha opinião, posso estar completamente, redondamente (ou quadradamente) errado, kkkk.

**Comment by cezarmzz** [comment]
RodriAndreotti, também acredito que pelo estado atual do projeto, manter ele em JS puro seja a melhor abordagem.
O Filipe e o Luciano começaram em JS e criaram esse projeto como uma iniciativa para que todos que quisessem participar de um projeto Open Source como a menor curva de aprendizagem possível.
Eu entendo também que quem está vindo de alguma linguagem fortemente tipada, como o Java ou C# pode ter um pouco de problemas, mas nada que estudar como funcionam as tipagens dinamicas do JS e também como funcionam outras partes triviais como promises, async/await, estruturas de repetição e estruturas condicionais aplicando o JS, vai conseguir a maioria dos problemas por aqui :)

**Comment by LeonardoRosaa** [comment]
@RodriAndreotti cara... concordo com você agora haha, não tinha pensado no ponto em que talvez se melhorasse manual de contribuição e coisas do tipo já pode ser "pego" alguns problemas com reviews e etc. Talvez podemos levantar esse ponto de migração para TypeScript mais pra frente. Belezaaa?

**Comment by RodriAndreotti** [comment]
Sim, exato!
Eu acho super válido a gente pensar em tornar o projeto mais robusto, e se o TypeScript ajudar nisso, ótimo, porque não? Mas acho que isso pode ser feito quando a comunidade já estiver mais amadurecida, com um pessoal que já aprendeu bem o básico e está pronto para dar o próximo passo, porque não ser este o próximo passo? Saca?
Babysteps... kkk

**Comment by LeonardoRosaa** [comment]
Na minha opinião, acho válido as práticas e possibilidades que o TypeScript trás para um projeto para todos os níveis devs. Mas acho que talvez nesse momento poderia até ser colocado em um roadmap ou algo assim sobre essa migração.

**Comment by RodriAndreotti** [comment]
Exato!
É como falei, reduzir a curva de aprendizado, assim se torna um circulo virtuoso, quando a pessoa terminar um módulo, ela pode pensar, e se eu fizer agora uma refatoração aqui para usar um typescript, e ai ele entra nessa curva de aprendizagem, e depois, e se eu fizer um promise aqui? e assim vai indo... rs
