### ISSUE TITLE
[SWAGGER] - Adicionar Documentação via Swagger

### ISSUE THREAD

**Issue by victor-ccab** [BrasilAPI/BrasilAPI#269]
* Dei uma breve olhada no projeto e não encontrei uma documentação **viva** das APIs.
* Caso ainda não tenha, não seria uma boa adicionar pelo menos um swagger auto-gerado via reflection? Assim como é feito no NestJS, entre outros frameworks...
* _OBS.: Vi as explicações de uso no README, mas elas não necessariamente refletem a realidade_

[]'s

**Comment by RodriAndreotti** [comment]
Opa... 
Tudo bem, Victor?
Cara, o pior é que tem, talvez esteja faltando colocar um link para ela no home, mas vc consegue acessar aqui:
https://brasilapi.com.br/docs

**Comment by victor-ccab** [comment]
Boa @RodriAndreotti !! mandei o PR #270 adicionando la no readme

**Comment by leleofg** [comment]
@victor-ccab então já pode fechar a issue ;)
