### ISSUE TITLE
AAAAA 😍

### ISSUE THREAD

**Issue by lucianopf** [BrasilAPI/BrasilAPI#3]
Pooouts mano, que irado!!! 
Ta mto lindo isso, NOW é mto delicinha! 😱 

Poxaaan o Github tinha que ter um chat pra gente trocar ideias sobre isso 😢

**Comment by CarlosZiegler** [comment]
Comentando aqui so para voces lembrarem quando o projeto tomou forma, minha primeira issue foi a 12, tem ate um PR la,  ate entao, salvo engano,  tinha so a do @filipedeschamps  e @lucianopf , posso dizer que quando cheguei isso aqui era tudo mato? 
Hahah

**Comment by RodriAndreotti** [comment]
Acho que dá para falar isso sim... kkk
