### ISSUE TITLE
Busca de CNPJ

### ISSUE THREAD

**Issue by Slender1808** [BrasilAPI/BrasilAPI#316]
Uma forma de encontrar CNPJ através de nome ou telefone.

**Comment by Mulequehype** [comment]
Tchau kkk

**Comment by Slender1808** [comment]
Não seria melhor discutir sobre Isso no Slack ?

**Comment by Liedsonrm** [comment]
Tu tem alguma ideia de como fazer isso? Gostei da ideia.

**Comment by Slender1808** [comment]
> Tu tem alguma ideia de como fazer isso? Gostei da ideia.

pensei em usar sqlite pra fazer busca

**Comment by Slender1808** [comment]
fiz esse protótipo usado sqlite com fts5 ficou com tamanho de 5g usando dataset do [https://brasil.io/dataset/socios-brasil/files/](https://brasil.io/dataset/socios-brasil/files/)
link com codigo que do teste está nesse repositório [https://github.com/Slender1808/Search-CNPJ](https://github.com/Slender1808/Search-CNPJ)

![Captura de tela de 2021-07-04 21-45-51](https://user-images.githubusercontent.com/50336793/124404429-482ca500-dd11-11eb-8677-b45299dd0aa2.png)

**Comment by Slender1808** [comment]
seria interessante se tiver algum forma de fazer busca eficiente no Firestore

**Comment by RodriAndreotti** [comment]
Cara, me tira uma dúvida, não seria possível utilizar o endpoint que o @cuducos  (`/cnpj`)criou para fazer essa filtragem, assim aproveitaria o retorno do serviço dele para criar o endpoint da sua ideia?

**Comment by lucianopf** [comment]
Bom dia mestre, tendo em vista que o projeto usa a Vercel + Next como base, será que faz sentido em lambdas hospedar esse tipo de informação?

A princípio o projeto tinha como premissa centralizar e simplificar consultas em diversas APIs externas e talvez se tornar uma API de dados não seja muito bem a proposta do projeto =/

**Comment by Slender1808** [comment]
> Cara, me tira uma dúvida, não seria possível utilizar o endpoint que o @cuducos (`/cnpj`)criou para fazer essa filtragem, assim aproveitaria o retorno do serviço dele para criar o endpoint da sua ideia?

**Comment by Slender1808** [comment]
> Bom dia mestre, tendo em vista que o projeto usa a Vercel + Next como base, será que faz sentido em lambdas hospedar esse tipo de informação?
> 
> A princípio o projeto tinha como premissa centralizar e simplificar consultas em diversas APIs externas e talvez se tornar uma API de dados não seja muito bem a proposta do projeto =/

Séria possível fazer função lambda que busca no SQLite porém existe limite no tamanho de arquivos que impede isso
