### ISSUE TITLE
Migrar ramificação principal de master para main

### ISSUE THREAD

**Issue by pedrosancao** [BrasilAPI/BrasilAPI#319]
Comentário do @hotieall na #318:  
> **Sugestão:** Por causa de uma mudança de terminologia que o Linus Torvalds, fez no Linux no ano passado. Hoje em dia não devemos usar o nome da branch principal com o nome de `master`, e renomea-la para `main`.

Já faz cerca de um ano que o GitHub fez essa mesma mudança, não tenho conhecimento sobre essa atualização do Linus. Está em tempo de fazermos a atualização aqui.

**Comment by RodriAndreotti** [comment]
Cara, na realidade não é que não devemos, somente recomendam não utilizar essa terminologia, porém, é possível utilizar qualquer nome que se desejar como ramificação principal, pessoalmente, não vejo a necessidade dessa mudança, visto que não sabemos qual o impacto que isso pode ter nos forks e PRs já existentes.

Enfim, minha opinião.

Aliás, este tema já tem um esboço de discussão rodando pelo repo, só não lembro onde.. .rs

**Comment by pedrosancao** [comment]
> Cara, na realidade não é que não devemos, somente recomendam não utilizar essa terminologia, porém, é possível utilizar qualquer nome que se desejar como ramificação principal, pessoalmente, não vejo a necessidade dessa mudança, visto que não sabemos qual o impacto que isso pode ter nos forks e PRs já existentes.

O termo master faz referência desnecessária à escravidão por ser associado ter associação master/slave, mesmo que no contexto do Git o conceito seja apresentado _remotes_ a conexão da palavra existe e ela pode ser evitada. Quando rolou a mudança o GitHub criou vários redirecionamentos e atualizações de PRs para que quem decidir pela mudança possa fazer de forma transparente.

> Aliás, este tema já tem um esboço de discussão rodando pelo repo, só não lembro onde.. .rs

Procurei mas não achei, se alguém achar/lembrar linka aqui, por favor.

**Comment by RodriAndreotti** [comment]
Cara, eu sei qual o contexto da sugestão de alteração, mas acredito que para um projeto existente, principalmente um open source, existe um esforço grande para fazer essa mudança, se existirem realmente estas ferramentas que tornem o processo transparente, ótimo, nenhuma objeção para mudar, mas quando mudei um projeto que só eu tenho acesso, gastei algum tempo para fazer, seria interessante ter alguma referência de como isso iria funcionar para um projeto grande.

Achei este chore: https://github.com/BrasilAPI/BrasilAPI/pull/200
Infelizmente não consegui achar a issue correspondente, faz algum tempo já que alguém sugeriu, se não me engano foi alguém da própria pagar.me

**Comment by PauloGoncalvesBH** [comment]
Não tem esforço para fazer essa mudança, o github mesmo auxilia nela e é totalmente necessário que façamos.

Para entender leia mais em https://github.com/github/renaming/#renaming-existing-branches

Eu que abri o PR e dentro da Pagar.me somos favoráveis à essa mudança. Vou levar adiante a renomeação com o pessoal que possui permissão para tal.

**Comment by LeoFC97** [comment]
Acredito que esta issue possa ser fechada, essa alteracao ja foi realizada
