### ISSUE TITLE
API para Estado e Cidade

### ISSUE THREAD

**Issue by RafaelMD** [BrasilAPI/BrasilAPI#32]
O que acham de APIs para Estados e Cidades?

IBGE tem um:

https://servicodados.ibge.gov.br/api/v1/localidades/estados

https://servicodados.ibge.gov.br/api/v1/localidades/estados/35/municipios

**Comment by juniorpb** [comment]
Acho legal a ideia de listar as cidades por estado, mandei uma pull request aplicando isso.

[(https://github.com/filipedeschamps/BrasilAPI/pull/33)]

**Comment by mukaschultze** [comment]
> Acho legal a ideia de listar as cidades por estado, mandei uma pull request aplicando isso.
> 
> [(https://github.com/[/pull/33](https://github.com/filipedeschamps/BrasilAPI/pull/33))]

Coloca #NumeroDoPR pra linkar o PR, por exemplo #33, dai ja aparece lá no outro tb que foi linkado, fica a dica.

**Comment by iuryLandin** [comment]
Seria interessante nessa API retornar também o DDD do estado

**Comment by mukaschultze** [comment]
> Seria interessante nessa API retornar também o DDD do estado

Maioria dos estados tem mais de um DDD, talvez um endpoint de DDDs fosse mais interessante

**Comment by mukaschultze** [comment]
Tava vendo aqui dos DDDs e achei [esse site](http://www.ddi-ddd.com.br/Codigos-Telefone-Brasil/), e [esse outro](https://www.vidadeturista.com/ddds-do-brasil), eles são bem completos e tem todas as cidades, talvez com um scrapping daria pra pegar todos os dados.

Daria pra criar duas APIs, uma que retorna as cidades com parâmetro um DDD, e outra que retorna um DDD e parâmetro a cidade.

Eu não faço a minima ideia com que frequência os DDDs mudam, as acho que não mudam nunca, alguém sabe informar isso?

**Comment by juniorpb** [comment]
Estou analisando retornar cidades por meio do DDD, estou aplicando nesse projeto:
[](https://github.com/juniorpb/cidades-promise)
É o mesmo que usei na pull request #33 

toda dica/critica é bem vinda.

**Comment by FCarvalhoVII** [comment]
> Eu não faço a minima ideia com que frequência os DDDs mudam, as acho que não mudam nunca, alguém sabe informar isso?

Os DDDs são como os próprios CEPs, foram ordenados com base no desenvolvimento de cada estado, eles não mudam nunca (a não ser que façam uma reformulação completa, coisa que nunca aconteceu), mas podem ser criados novos DDDs o que não acontece muito. A ideia de retornar os DDDs é interessante, mas acredito que ela deve ser vinculada a cidade e não ao estado, porque um estado possui uma quantidade muito grande de DDDs e essa informação é meio desnecessária em um âmbito estadual.

**Comment by VictorGaiva** [comment]
Não seria melhor vincular o DDD ao CEP em si? Acredito que seria mais robusto.

**Comment by juniorpb** [comment]
Sim, mas há cenários que buscar por DDD é mais preciso, por exemplo: Um plano de operadora para celular nas cidades com DDD 21. A rota proposta é [essa](https://brasilapi-git-fork-juniorpb-actions.filipedeschamps.now.sh/api/cities/v1/ddd/21) da PR #35
