### ISSUE TITLE
Criar pacote para Flutter

### ISSUE THREAD

**Issue by biel-correa** [BrasilAPI/BrasilAPI#338]
A ideia seria criar um pacote para o Flutter em que todos os endpoints estariam listados. Isso veio a partir dos pacotes para o Firebase, nunca digito nenhum endpoint nem tenho que criar uma header para ter o desempenho de uma API.

Nisso eu gostaria de saber se mais alguém gosta da ideia, e se caso entre em desenvolvimento gostaria que o pacote tivesse o nome brasil_api (Estou perguntando porque não sei se existe alguma limitação de direitos ao nome).

**Comment by RodriAndreotti** [comment]
Seria uma espécie de sdk?
Se for um SDK me parece uma ideia bem interessante

**Comment by biel-correa** [comment]
Estava pensando em algo tipo isso

**Comment by RodriAndreotti** [comment]
Acho uma ideia bem legal, esperar o resto da galera se manifestar, mas abre até espaço para outros SDK's para outras linguagens tbm.

**Comment by lucianopf** [comment]
Interessante hein mano! :grimacing: 

A atualização dos métodos dele pra sincronizar com o BrasilAPI seria automática ou manual mesmo? :eyes: :star_struck:

**Comment by biel-correa** [comment]
A princípio manual, não conheço nada que deixe isso automático

**Comment by isorensen** [comment]
Pessoal, criei este pacote para facilitar minha vida com Bancos Brasileiros, usando o BrasilAPI, no flutter. Talvez seja um bom ponto de partida se alguém de vocês quiser contribuir e transformá-lo num pacote mais genérico.

Fiquem à vontade em fazer um fork e iniciar o novo projeto.

https://pub.dev/packages/brazilian_banks

**Comment by biel-correa** [comment]
Eu quero muito montar isso, mas trabalhar e estudar me deixa totalmente sem tempo, mas assim que puder eu vou aproveitar algo seu sim. Dei uma olhada no que já tem aqui e gostei bastante 👌👌.

**Comment by isaqueveras** [comment]
Olá pessoal, aproveitando o assunto quero deixar aqui minha lib que fiz em Go para se comunicar com o BrasilApi, até agora só implementei o endpoint do CEP.

Fiquem a vontade pra deixar sua sujestão/melhoria lá no **[brasilapi-go](https://github.com/isaqueveras/brasilapi-go)**
