### ISSUE TITLE
[BUG] Bug no que parece ser alguma configuração do Cloudflare

### ISSUE THREAD

**Issue by yardz** [BrasilAPI/BrasilAPI#339]
Ao acessar o endpoint de CEP o cloudflare está bloqueando a requisição.
A requisição também é bloqueada quando é feita diretamente pelo node... Sem o cloudflare até da pra conviver, mas sem conseguir fazer requisições do node (em ambiente local) é bem problematico.

Quando faço deploy do código, funciona normalmente.

<img width="1132" alt="Captura de Tela 2021-08-24 às 1 51 43 AM" src="https://user-images.githubusercontent.com/1014611/130558113-9f3ab904-db17-4c08-97e9-dad09ee7ba64.png">

**Comment by murilohns** [comment]
@yardz acredito que seja um problema do seu ambiente local, pode dar uma olhada [nesse artigo](https://blog.postman.com/self-signed-ssl-certificate-troubleshooting/), por favor?

**Comment by lucianopf** [comment]
Oloooco 525 é coisa só da Cloudflare mesmo :thinking: 

Será que não era uma indisponibilidade na hora? Agora já voltou a funcionar?

**Comment by RodriAndreotti** [comment]
Na realidade, acho que o erro 525 geralmente significa que a comunicação entre o cloudflare e o servidor de origem teve um problema:
https://support.cloudflare.com/hc/pt-br/articles/115003011431-C%C3%B3mo-solucionar-errores-5XX-de-Cloudflare#525error

Não sei se na Vercel usamos Let's Encrypt ou outro serviço com renovação automática, se for talvez o acesso tenha sido feito no exato momento em que o certificado estava sendo renovado.

**Comment by yardz** [comment]
> @yardz acredito que seja um problema do seu ambiente local, pode dar uma olhada [nesse artigo]

Cara, eu acho que foi no cloudflare mesmo. Eu não fiz nenhuma alteração no computador (nem o postman eu fechei) e hoje mais cedo testei e funcionou (e está funcionando agora). Literalmente o problema desapareceu...

> Oloooco 525 é coisa só da Cloudflare mesmo 🤔
> 
> Será que não era uma indisponibilidade na hora? Agora já voltou a funcionar?

Agora está normal, rápido e bonito rsrs. Eu fiquei preocupado pois gastei algumas horas com isso...
Mas voltou a funcionar bunitinho :-)




> Na realidade, acho que o erro 525 geralmente significa que a comunicação entre o cloudflare e o servidor de origem teve um problema:
> https://support.cloudflare.com/hc/pt-br/articles/115003011431-C%C3%B3mo-solucionar-errores-5XX-de-Cloudflare#525error
> 
> Não sei se na Vercel usamos Let's Encrypt ou outro serviço com renovação automática, se for talvez o acesso tenha sido feito no exato momento em que o certificado estava sendo renovado.

Cara, eu desconheço o  Let's Encrypt. Você sabe dizer se essa instabilidade duraria horas? Pq eu fiquei com esse problema por várias horas....


@lucianopf se quiser pode fechar essa issue pois o problema desapareceu e não sei se é vale a pena tentar encontrar a causa raiz disso.

**Comment by RodriAndreotti** [comment]
> Cara, eu desconheço o Let's Encrypt. Você sabe dizer se essa instabilidade duraria horas? Pq eu fiquei com esse problema por várias horas....

Cara, basicamente a renovação automática é feita por uma tarefa agendada que chama o certbot ou o acme (que são os aplicativos que criam o certificado) alguns dias antes do certificado expirar, este processo não demora mais do que 2 a 3 minutos, mas como o CloudFlare faz cache de requisições, talvez possa ser algo relacionado.

**Comment by yardz** [comment]
> Cara, basicamente a renovação automática é feita por uma tarefa agendada que chama o certbot ou o acme (que são os aplicativos que criam o certificado) alguns dias antes do certificado expirar, este processo não demora mais do que 2 a 3 minutos, mas como o CloudFlare faz cache de requisições, talvez possa ser algo relacionado.

Entendi... Eu não "chutaria" que era isso pois no navegador funcionava normalmente... :-/

**Comment by RodriAndreotti** [comment]
> > Cara, basicamente a renovação automática é feita por uma tarefa agendada que chama o certbot ou o acme (que são os aplicativos que criam o certificado) alguns dias antes do certificado expirar, este processo não demora mais do que 2 a 3 minutos, mas como o CloudFlare faz cache de requisições, talvez possa ser algo relacionado.
> 
> Entendi... Eu não "chutaria" que era isso pois no navegador funcionava normalmente... :-/

Ai você me pegou... kkk
Se no navegador funcionava, não teria lógica não funcionar em outros lugares, principalmente pelo código do erro, mas, se voltar a acontecer, acho que será um debug que talvez seja necessário dar mais atenção.

**Comment by SweetSoul** [comment]
@yardz Se tiver tudo certo então, fecha a issue pra nós 😄
