### ISSUE TITLE
Coordenadas pelo o CEP

### ISSUE THREAD

**Issue by matheusoluz** [BrasilAPI/BrasilAPI#34]
Acredito que agregaria muito valor adicionar a funcionalidade retornar as coordenadas dado o input de um cep. 

Segue abaixo um projeto que já tenta resolver esse problema: 

coordenadas-do-cep:
[Github](https://github.com/viniciusm2001/coordenadas-do-cep)
[NPM](https://www.npmjs.com/package/coordenadas-do-cep)

**Comment by thiagoargolo** [comment]
[CEP aberto](http://cepaberto.com/)?

**Comment by lucianopf** [comment]
Muito boa a ideia galera!! 👏 🚀 

Só vou trazer alguns pontos que acho relevantes pra essa discussão:
- Curti o projeto do npm, legal a ideia, só me preocupa um pouco apenas se basear no ViaCep, hoje em dia ele anda bem instável como provedor do `cep-promise`, quando o número de requisições se torna alto ele muitas vezes responde com 502 😢  (que é uma pena, pq é um serviço sensacional!)

- O cep-aberto é beeem legal, mas é outro provider que tive que tirar do `cep-promise` pq constantemente invalidava a nossa api key, pq provavelmente a gnt batia no limite de requisições muito rápido 😨

**Comment by farukaf** [comment]
@lucianopf não seria possivel criar uma extensão/override e possibilitar fornecer um api-key de quem esta consumindo?

**Comment by juloko** [comment]
Acho que mais que uma coordenada um cep deveria ser definido por uma curva. Seria interessante obter o trajeto por onde todo o cep é definido. Óbvio que está num passo muito mais adiante e que primáriamente já obter uma geolocalização é o primeiro passo.

A exemplo disso que o Google Maps já faz, seria possível interfacear as duas apis?

![image](https://user-images.githubusercontent.com/17098382/83669338-c6b39200-a5a7-11ea-844b-44d6bf93258c.png)

**Comment by ivanmonteiro** [comment]
Google e Bing possuem apis para isso. A questão é o custo disso, existem limites que caso excedidos geram gastos.

**Comment by juloko** [comment]
@ivanmonteiro eles possuem API com CEP? Acho que apenas pelo endereço, e eles não indexam bem CEP, então seria interessante casar as duas coisas. (acho)

**Comment by ivanmonteiro** [comment]
> @ivanmonteiro eles possuem API com CEP? Acho que apenas pelo endereço, e eles não indexam bem CEP, então seria interessante casar as duas coisas. (acho)

Pelo menos o google aparentemente possui sim suporte a CEP retornando latitude e longitude
https://pt.stackoverflow.com/questions/130278/converter-cep-para-latitude-e-longitude-javascript/130329
Bing maps não cheguei a testar mas é possível que retorne a latitude e longitude caso o cep seja fornecido

**Comment by ivanmonteiro** [comment]
Quanto a precisão disso não sei te dizer

**Comment by juloko** [comment]
@ivanmonteiro 
Quoted from: https://pt.stackoverflow.com/questions/130278/converter-cep-para-latitude-e-longitude-javascript/130329

`````
Acesse a URL abaixo:

https://maps.googleapis.com/maps/api/geocode/json?address=SEU_CEP&key=SUA_API_KEY
Ela vai retornar um JSON contendo o endereço completo e latitude e longitude.

Para essa URL funcionar, você precisa ter uma conta no Google Developers Console. 
E essa conta precisa ter um cartão de crédito cadastrado. 
O valor é de aproximadamente US$ 7,00 a cada 1.000 requisições.

A sua API_KEY tem que ter habilitada a Maps Javascript API e Geocode API
`````

Isso já aconteceu comigo, estou desenvolvendo um serviço de notícias que precisa de interpretação em inglês, mas as notícias são em português, após brincar por uma semana tive que pagar 70,00 reais ao Google. 

Para contornar situação usei uma API gratuita que provavelmente usa o Google Tradutor online, no entanto é limitado em 1500 caracteres e meus textos eram maiores que isso. Então cortei os parágrafos e fiz diversas requisições. Valeu apena, deixou de frustrar um projeto. 

Esse mínimo custo frustra quem está na etapa de teste. Então talvez seja uma boa.

**Comment by ivanmonteiro** [comment]
https://cepaberto.com/
Não testei ainda mas achei esse projeto interessante, tem uma api e uma base de dados com ceps geolocalizados.

**Comment by LorhanSohaky** [comment]
Estou trabalhando num projeto pessoal para fazer isso. A ideia que tive é um pouco trabalhosa e com possibilidade de dados inconsistentes. O que estou fazendo é a partir do cep pegar o endereço e com o endereço consultando no open street map a geolocalização.

**Comment by RodriAndreotti** [comment]
Eu deixei de utilizar o serviços de mapa e geocoding do google e estou usando os do Here Maps, ele tem uma quantidade de requests razoável e é razoavelmente preciso, para o que preciso, claro, e, se for o caso, dá para fazer ajustes finos no mapa usando o marcador deles com callback

**Comment by LorhanSohaky** [comment]
Criei um PR #117 para a API também retornar a localização
