### ISSUE TITLE
CNPJ ativo não encontrado

### ISSUE THREAD

**Issue by isorensen** [BrasilAPI/BrasilAPI#360]
# Sumário

Em consulta a um CNPJ utilizando o endpoint `https://brasilapi.com.br/api/cnpj/v1/{cnpj}` houve um retorno de "não encontrado", de uma empresa que está cadastrada na base da receita desde março/2021.

## Steps to Reproduce

1. Fazer a consulta de `https://brasilapi.com.br/api/cnpj/v1/41199206000170`

### Resultado obtido

`{"message":"CNPJ 41.199.206/0001-70 não encontrado.","type":"not_found","name":"NotFoundError"}`

### Resultado esperado

Retornar com as informações do CNPJ da empresa. Vide imagem abaixo, comprovando que a empresa está cadastrada na base da receita desde março/2021.

![image](https://user-images.githubusercontent.com/3399976/143250797-21dabb69-dffb-4050-96c7-8abed236d0c4.png)

## Sugestão de melhoria

Incluir na documentação da API qual a frequencia de atualização dos dados.

**Comment by RodriAndreotti** [comment]
Fala @cuducos !
Consegue dar um help nisso?

**Comment by cuducos** [comment]
> desde março/2021

[Estou tentando](https://github.com/cuducos/minha-receita/issues/37).

**Comment by isorensen** [comment]
> > desde março/2021
> 
> [Estou tentando](https://github.com/cuducos/minha-receita/issues/37).

Massa. Não tinha visto a issue relacionada. Vou fechar esta issue então, considerando que já está endereçada, e apenas ressalto que a gente usa bastante, mas obviamente é um problema pra gente estar tão descasado com as novas empresas.

**Comment by RodriAndreotti** [comment]
> > ressalto que a gente usa bastante
> 
> Fico muito feliz em saber, ganhei meu dia purple_heart
> 
> O foda é que estou sem tempo, e o [financiamento coletivo do Minha Receita](https://docs.minhareceita.org/) (API que o BrasilAPI utiliza) anda bem minguado — aí não consigo me dedicar, nem contratar alguém para me ajudar a atualizar o projeto. A Receita mudou o formato de repente e me pegou de surpresa : (
> 
> Mas assim que esse refactor estiver concluído, vai dar para automatizar e manter atualizado sempre que a Receita soltar novas versões dos dados!

Cara, se eu estivesse com tempo contribuiria sem problema, mas o mal dos tempos modernos (a falta de tempo) tbm me atinge... rs
