### ISSUE TITLE
Erro em CEP válido

### ISSUE THREAD

**Issue by vilsongabriel** [BrasilAPI/BrasilAPI#367]
Estava utilizando a API v2 de CEP e recebi uma reclamação que para o CEP "[92425090](https://brasilapi.com.br/api/cep/v2/92425090)" não estava retornando.

Fiz o teste e retorna o erro "Todos os serviços de CEP retornaram erro.", porém ao tentar consultar na [ViaCEP, por exemplo](https://viacep.com.br/ws/92425090/json/), os dados são retornados normalmente.

**Comment by lucianopf** [comment]
Mestre, dei uma olhadinha aqui e acredito que ou o serviço faz cache de um conjunto de erros (é improvável pq são alguns provedores) ou o cep é novo e havia sido consultado antes de ser atualizado nos serviços e isso está em cache.

Fiz uma busca aqui adicionando uma querystring qualquer pra buscar sem considerar a CDN e encontrou sem problemas.
Vc sabe se esse é um cep novo mestre? :pray: 

![image](https://user-images.githubusercontent.com/8251208/148114330-5c67f05d-918f-4f28-8277-e70bf8a45910.png)

**Comment by vilsongabriel** [comment]
Que bacana a possibilidade da querystring na consulta, não sabia.

Quanto ao CEP ser novo, infelizmente não sei dizer, só me foi passado que um cliente estava tendo problemas com esse CEP.

**Comment by Nerd00F** [comment]
Testei aqui e também deu certo, você tentou consultar novamente?

**Comment by vilsongabriel** [comment]
> Testei aqui e também deu certo, você tentou consultar novamente?

Fiz o teste novamente aqui e parece estar ok agora. Deve ter sido algum problema pontual com o cache mesmo, por hora vou fechar essa issue.
