### ISSUE TITLE
Guia de estilos

### ISSUE THREAD

**Issue by RaphaelOliveiraMoura** [BrasilAPI/BrasilAPI#37]
Sou novato aqui galera, to conhecendo o projeto agora e estou super disposto a contribuir no que estiver ao meu alcance.

Não conheço muito das funcionalidades do Next porém não vi nenhum arquivo de configuração de linting no projeto. Qual a opinião de vocês sobre isso ?

Creio que vale a pena configurar esses padrões de estilo de código, principalmente no inicio do projeto. Pois no futuro adicioná-los será bem mais trabalhoso.

**Comment by mathleite** [comment]
Olá, acabei conhecendo o projeto ao acaso e também estou disposto a contribuir.

Concordo com você, o quanto antes *"colocarmos"* esse `linter` melhor. Até por que a gente consegue controlar a qualidade do código como um todo. :)

**Comment by paulogdm** [comment]
Que tal uma enquete?
Meu voto iria pro padrão Airbnb :hand:

**Comment by paulo-santana** [comment]
Como funciona a implementação disso num projeto público que tem PRs abertos? Tem que esperar fechar todos pra rodar eslint?

**Comment by filipedeschamps** [comment]
@paulogdm topo também Airbnb, assim volto a me forçar a usar `;` no código 😂 

@paulo-santana se o linter for implementado depois, inclusive com bloqueio no CI, os PR abertos precisam ter a master merged ou rebased de volta  👍

**Comment by lucianopf** [comment]
@filipedeschamps faço suas as minhas palavras kkkk, pra usar `;` só com linter gritando comigo msm hehehe

@paulogdm curto bastante o Standardjs, mas to curtindo a ideia de ir de Airbnb, faz tempo que não uso esse 😬🚀 

Boa galera, topam puxar então um PR que adiciona o linter no repo? 😬

**Comment by RaphaelOliveiraMoura** [comment]
@lucianopf Com certeza !!

**Comment by juloko** [comment]
Putz, @filipedeschamps justamente quando devido a ti eu estava pensando em parar de usar.
