### ISSUE TITLE
Erro em lista de cidades por UF

### ISSUE THREAD

**Issue by vdurvalino** [BrasilAPI/BrasilAPI#382]
O endpoint https://brasilapi.com.br/api/ibge/municipios/v1/SP não retorna a cidade de São Paulo

**Comment by lucianopf** [comment]
Caraaaaca mestre, vdd! 😱 

Vou dar uma olhadinha 🙏

**Comment by lucianopf** [comment]
Ta, acho que entendi @vdurvalino , a fonte desse endpoint é a Wikipedia, e lá de fato não ta constando São Paulo como cidade contida no estado de São Paulo 😢 

Pra resolver isso alguém teria que propôr uma edição no artigo lá adicionando a cidade =/
https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_de_S%C3%A3o_Paulo

**Comment by RodriAndreotti** [comment]
Eu não sei se alguém já sugeriu a edição:
![image](https://user-images.githubusercontent.com/9449048/157031530-6830cf4b-9de6-4673-b553-85eb91212a4d.png)
Mas na pagina de edição do artigo já consta.

**Comment by lucianopf** [comment]
Ué, vc tem razão! 🤔  

E não parece ter sido adicionado agora não, acho que eu que não tinha visto mesmo 🤔 

Bem... ta com cara de bug nosso então mesmo, simbora investigar! 🔍

**Comment by vdurvalino** [comment]
Não sei se isso já foi discutido antes mas o IBGE tem uma API..

Será que não seria o caso de buscar esses dados de lá não?

https://servicodados.ibge.gov.br/api/docs/localidades

**Comment by RodriAndreotti** [comment]
> Ué, vc tem razão! thinking
> 
> E não parece ter sido adicionado agora não, acho que eu que não tinha visto mesmo thinking
> 
> Bem... ta com cara de bug nosso então mesmo, simbora investigar! mag

Uma coisa que percebi é que o ctrl + F não o encontra, talvez esteja com algum typo com caractere invisível que esteja fazendo dar B.O.

**Comment by RodriAndreotti** [comment]
> Não sei se isso já foi discutido antes mas o IBGE tem uma API..
> 
> Será que não seria o caso de buscar esses dados de lá não?
> 
> https://servicodados.ibge.gov.br/api/docs/localidades

É uma possibilidade, só precisaríamos filtrar pelo UF na mezzo-região, acho até uma fonte mais confiável e atualizada, e talvez usar a wikipedia como fallback.

**Comment by LorhanSohaky** [comment]
> Não sei se isso já foi discutido antes mas o IBGE tem uma API..
> 
> Será que não seria o caso de buscar esses dados de lá não?
> 
> https://servicodados.ibge.gov.br/api/docs/localidades

A API do IBGE já é usada. Em teoria a API do Wikipedia só é chamada quando a do IBGE falha [link do código](https://github.com/BrasilAPI/BrasilAPI/blob/main/pages/api/ibge/municipios/v1/%5Buf%5D.js#L8). Se achar interessante você pode abrir um PR colocando o [dados abertos br](http://educacao.dadosabertosbr.com/api/docs/%2Fapi%2Fcidades%2F%7Bestado%7D) como provider.
