### ISSUE TITLE
Busca IBGE: UF (código divergente)

### ISSUE THREAD

**Issue by WellingtonFonseca** [BrasilAPI/BrasilAPI#389]
pessoal, rodei um processo aqui para adquirir os códigos IBGEs para uma listagem de cidades e notei que o resultado está inválido.
no exemplo abaixo estou utilizando a cidade de `Barueri` como exemplo, mas está ocorrendo para muitos outros:

```
GET https://brasilapi.com.br/api/ibge/municipios/v1/SP
```
resultado:

![Captura de Tela-20220328161958-261x63](https://user-images.githubusercontent.com/25608175/160472313-26f4ae5b-e4d5-46da-bbf9-3c4e7645c184.png)

notem que há um **05** na frente do código, porém ao consultar o site do **IBGE** e o **WiKi** (que até onde entendi a consulta é feita lá), o resultado está divergente:

![Captura de Tela-20220328162954-458x188](https://user-images.githubusercontent.com/25608175/160472472-57c06a32-afc3-4ba1-957e-3afd645313d5.png)

![Captura de Tela-20220328163108-613x180](https://user-images.githubusercontent.com/25608175/160472624-266ff0be-a2ab-4dce-9e3d-2c259108491e.png)

acabei de consultar a api do IBGE e lá também está OK
```
https://servicodados.ibge.gov.br/api/v1/localidades/estados/SP/municipios
```

![Captura de Tela-20220328164438-366x62](https://user-images.githubusercontent.com/25608175/160474911-96c1807c-9ad7-4910-8357-d283cfd24360.png)

**Comment by murilohns** [comment]
Que bizarro
Ainda mais pq usamos a API do IBGE pra fazer essa consulta 😂

**Comment by murilohns** [comment]
Achei o problema, estamos pegando o ID do site do IBGE, invés do `municipio,id`
![image](https://user-images.githubusercontent.com/18074134/160475667-9e26aeaa-9de6-4b16-87b8-818f5d9b9e7b.png)

**Comment by WellingtonFonseca** [comment]
sim, vim aqui pra dizer isso, estão utilizando o id errado.
o que seria essa quebra de interface? quer dizer que a api pode não ter o mesmo padrão para outras cidades?

por hora, estou utilizando a api do IBGE mesmo
