### ISSUE TITLE
Melhoria na documentação da Brasil API

### ISSUE THREAD

**Issue by Cristianpl4y** [BrasilAPI/BrasilAPI#397]
Primeiramente parabéns a todos os envolvidos muito bacana esse projeto, sugiro como melhoria na documentação colocarem exemplos de como fazer uma requisição pois hoje só tem as responses para quem é iniciante fica difícil entender.

**Comment by murilohns** [comment]
@Cristianpl4y, você consegue explicar melhor como melhorar a docs?
Na documentação tem o endpoint, com o exemplo de requisição, e o exemplo de resposta
![image](https://user-images.githubusercontent.com/18074134/166249308-ed55eb00-cee9-4164-b4f8-6b258ae204f5.png)

**Comment by Cristianpl4y** [comment]
Opa, tudo certo ? @murilohns 
Digo um exemplo de envio da requisição, para tentar explicar melhor olhando na documentação da ZENVIA eles fazem isso:  [https://zenvia.github.io/zenvia-openapi-spec/v2/#tag/SMS/paths/~1channels~1sms~1messages/post](url)

No print em vermelho tem um exemplo de como e montada a requisição isso que eu digo. 
![exemplo](https://user-images.githubusercontent.com/55006128/166336180-29c0993c-fcad-4613-afba-d02c654aab00.png)

E logo depois vem a response. 

Falta isso na documentação da Brasil API, acredito que para quem tem pouco conhecimento isso ajuda bastante.

Se ainda tiver duvidas pode me chamar no whats 55 997101586  que tento te explicar melhor.

**Comment by alan-christian** [comment]
@Cristianpl4y está exatamente documentado como no exemplo que você trouxe, primeiro a url de request é mostrada, e em seguida é mostrado o response gerado
