### ISSUE TITLE
Erro pra consultar serviço da WideNet

### ISSUE THREAD

**Issue by belemlc** [BrasilAPI/BrasilAPI#398]
Existe um cep que pela WideNet está sendo localizado, mas quando tenta se conectar no servidor deles está retornando esse erro: Erro ao se conectar com o serviço WideNet.

**Comment by murilohns** [comment]
@belemlc, qual o CEP? Pode dar mais informações, por favor?

**Comment by belemlc** [comment]
Fala ae @murilohns, quando tento consultar esse cep **78890000**, dá um erro para todos os serviços **correios, viacep e WideNet**, sendo que quando consulto direto pelo WideNet retorna resultado.

[(WideNet: https://ws.apicep.com/cep.json?code=78890000)]

Quanto o erro, retorna esse:

`{
"name": "ServiceError",
"message": "Erro ao se conectar com o serviço WideNet.",
"service": "widenet"
}`

mas percebi que para os outros também retorna a mesma coisa, só não sei se de fato estão usando a mesma api, porque pelo que vi, a WideNet que mantém a **[apicep](https://apicep.com/)**

**Comment by belemlc** [comment]
@murilohns sim, faz todo sentido, inclusive eu tomei um block de flood deles fazendo testes, mas obrigado pela resposta, achei muito bacana essa iniciativa.

**Comment by RodriAndreotti** [comment]
Bom dia, pessoal!
@murilohns, realmente, tem razão, acho que tem algum erro neste CEP.
Acabei de consultar diretamente no site dos correios e não há dados para este cep, será que ele ainda existe?
