### ISSUE TITLE
Quantidade de requests

### ISSUE THREAD

**Issue by EttoreBotelho** [BrasilAPI/BrasilAPI#402]
Boa tarde.
Gostaria de saber a quantidade de requests por minuto que podem ser feitos.
Tenho uma lista de CNPJ e preciso extrair os CNAEs de cada empresa.
Parabéns pela iniciativa da API, muito útil.

**Comment by LorhanSohaky** [comment]
@lucianopf , @murilohns , vocês têm noção desse número? Ou quem controla isso é a própria cloudflare

**Comment by LorhanSohaky** [comment]
@EttoreBotelho , mas quantos CNPJs você tem nessa lista?

**Comment by EttoreBotelho** [comment]
> @EttoreBotelho , mas quantos CNPJs você tem nessa lista?

Seria uma lista com aproximadamente 5.000 endereços.
Mas teria que repetir esse processo com outros endereços uma  vez por semana mais o menos.

**Comment by EttoreBotelho** [comment]
> @EttoreBotelho , mas quantos CNPJs você tem nessa lista?

Seria uma lista com aproximadamente 5.000 endereços.
Mas teria que repetir esse processo com outros endereços uma vez por semana mais o menos.

**Comment by LorhanSohaky** [comment]
> > @EttoreBotelho , mas quantos CNPJs você tem nessa lista?
> 
> Seria uma lista com aproximadamente 5.000 endereços. Mas teria que repetir esse processo com outros endereços uma vez por semana mais o menos.

Acredito que possa fazer isso, minha sugestão é que faça em lotes de 10 CNPJs com intervalo de alguns segundos (ex. 3 segundos)

mais ou menos assim:
1. 10 requests em paralelo
2. espera 3 segundos
3. 10 requests em paralelo
e assim por diante

**Comment by LorhanSohaky** [comment]
> > @EttoreBotelho , mas quantos CNPJs você tem nessa lista?
> 
> Seria uma lista com aproximadamente 5.000 endereços. Mas teria que repetir esse processo com outros endereços uma vez por semana mais o menos.

Só q

> > @EttoreBotelho , mas quantos CNPJs você tem nessa lista?
> 
> Seria uma lista com aproximadamente 5.000 endereços. Mas teria que repetir esse processo com outros endereços uma vez por semana mais o menos.

Só deixaria como observação que se não me engano esses dados de receita federal não atualizam toda semana, então poderia fazer essas requisições uma vez por mês
