### ISSUE TITLE
Endpoint: GET api/feriados/v1/2022, falta feriado "sexta feira santa/paixão de cristo"

### ISSUE THREAD

**Issue by xnei** [BrasilAPI/BrasilAPI#403]
Pessoal, boa tarde! notei que o endpoint de feriados nacionais não está retornando a sexta-feira santa, que em 2022 foi no dia 15 de abril. Seria um problema conhecido?

Abs,

**Comment by xnei** [comment]
Imagino que na implementação possam ter confundido com a quinta-feira santa (que de fato não é feriado nacional), mas pelo que eu pesquisei, a sexta seria feriado nacional sim, seguem algumas fontes:

https://editalconcursosbrasil.com.br/noticias/2022/04/sexta-feira-santa-e-feriado-nacional-ou-ponto-facultativo/
https://www.in.gov.br/en/web/dou/-/portaria-me-n-14.817-de-20-de-dezembro-de-2021-369345454

**Comment by gtomanini** [comment]
@murilohns reabrir?

**Comment by lucianopf** [comment]
Rapaz, pior que pela FBB tbm ta falando que é feriado, acho justo sim hein!

**Comment by RodriAndreotti** [comment]
> Rapaz, pior que pela FBB tbm ta falando que é feriado, acho justo sim hein!
> 
> https://feriadosbancarios.febraban.org.br/

Então, Pessoal!
Ontem dei uma pesquisada sobre isso quando vi que o issue foi fechado, o que achei foi:
A lei federal não fala que é feriado, fala que cada município tem autonomia para decidir se é o ou não.
Fontes:
http://www.planalto.gov.br/ccivil_03/leis/l9093.htm
http://cjpcontabil.com.br/boletim/feriados-nacionais-e-religiosos-21
https://www.solver-rh.com.br/boletim-49-feriados-no-brasil/



Porém eu nunca ouvi falar de nenhum município onde a sexta feira santa não seja considerado feriado, sendo assim, acho que é válido incluirmos ela, o que acham?

**Comment by RenatoBrunetti** [comment]
Pessoal. Adicionei o feriado de sexta-feira santa na aplicação.
[Pull Request](https://github.com/BrasilAPI/BrasilAPI/pull/408)

**Comment by LorhanSohaky** [comment]
> Pessoal. Adicionei o feriado de sexta-feira santa na aplicação. [Pull Request](https://github.com/BrasilAPI/BrasilAPI/pull/408)

Aprovado! Só acharia interessante se tiver um provedor de dados com essas informações atualizadas para que não tenhamos a responsabilidade de adicionar novas datas ou remover algumas
