### ISSUE TITLE
Cep está retornando erro

### ISSUE THREAD

**Issue by alezanchet** [BrasilAPI/BrasilAPI#417]
Algo aconteceu que para alguns ceps (como 94440000) a api agora só está retornando success quando o cep é enviado entre chaves

https://brasilapi.com.br/api/cep/v2/{94440000} FUNCIONA
https://brasilapi.com.br/api/cep/v2/94440000 NÃO FUNCIONA

**Comment by murilohns** [comment]
🤔 
![image](https://user-images.githubusercontent.com/18074134/187028935-31bbc4e2-2416-4db2-9ce7-c82225f93fb5.png)

**Comment by murilohns** [comment]
@alezanchet cê tá usando alguma configuração específica? não tá funcionando nem no navegador?

**Comment by lucianopf** [comment]
Só pra confirmar, vc mora no Brasil mestre?

**Comment by claudiocassimiro** [comment]
Tá funcionando pra mim, sugiro que essa issue seja fechada

**Comment by gtomanini** [comment]
Funcionando aqui também, não encontrei nenhuma outra evidência de problema
