### ISSUE TITLE
Documentação incorreta no endpoint de taxas.

### ISSUE THREAD

**Issue by farukaf** [BrasilAPI/BrasilAPI#420]
O endpoint responde com os campos em português. Porem na documentação consta os nomes em ingles.
![image](https://user-images.githubusercontent.com/19143772/189557514-e6b3963b-ef14-4972-a933-c0155fc30b3f.png)
Imagem da documentação
![image](https://user-images.githubusercontent.com/19143772/189557526-032f36a1-fe6d-4940-b461-b97ad6dc9a5e.png)
Imagem do retorno da API

**Comment by alan-christian** [comment]
corrigido -> #422

**Comment by alan-christian** [comment]
acho que ja pode fechar essa issue @lucianopf
