### ISSUE TITLE
Cliente python

### ISSUE THREAD

**Issue by lipe14-ops** [BrasilAPI/BrasilAPI#424]
Eu criei um client para a API pois achei muito interessante a ideia do projeto e não havia achado clients feitos em python, e aqui vai o repositório do cliente no [github](https://github.com/lipe14-ops/brasilapy).

**Comment by lucianopf** [comment]
Que massa mestre!! 😱 🚀 
Fica a vontade de abrir um PRzin [nessse molde aqui](https://github.com/BrasilAPI/BrasilAPI/pull/419) que daí fica direto no `README.md` na cara do repo pra galera usar tbm ^^

**Comment by lipe14-ops** [comment]
OPA tudo jóia ??? então fiz o PR a alguns dias... acabei enviando 2 foi mal este erro... mas de todo modo está tudo pronto apenas esperando a aprovação!!! obrigado.    : )
