### ISSUE TITLE
Email vindo null na busca de dados por  CNPJ

### ISSUE THREAD

**Issue by vspok** [BrasilAPI/BrasilAPI#430]
ao buscar dados por cnpj o email da empresa esta vindo NULL.
url https://brasilapi.com.br/api/cnpj/v1/{cnpj}

**Comment by henriquenasc** [comment]
Aparentemente é o retorno do próprio endpoint!
Eu tentei acessar direto por: https://minhareceita.org/CNPJ e também retorna NULL não apenas no e-mail, mas em outros locais também.

**Comment by vspok** [comment]
> Aparentemente é o retorno do próprio endpoint! Eu tentei acessar direto por: https://minhareceita.org/CNPJ e também retorna NULL não apenas no e-mail, mas em outros locais também.

sim fiz esse teste também,  mas pelo jeito uma opção de privacidade deles
 
https://docs.minhareceita.org/servidor/#questoes-de-privacidade

https://github.com/cuducos/minha-receita/issues/157

**Comment by murilohns** [comment]
Fechando a Issue devido ao [comentário](https://github.com/cuducos/minha-receita/issues/157#issuecomment-1278229692)
