### ISSUE TITLE
Sugestão de usar gRPC 

### ISSUE THREAD

**Issue by peeeuzin** [BrasilAPI/BrasilAPI#437]
gRPC é bem mais eficiente que HTTP e acho que seria uma boa a gente implementar isso, até porque tem várias aplicações que precisam de "rapidez" em resposta da API.

**Comment by LorhanSohaky** [comment]
Poderia falar um pouco mais sobre?

**Comment by peeeuzin** [comment]
RPC (Remote Procedure Call) é um protocolo (tipo HTTP) request-response bem eficiente que o HTTP. gRPC é um framework que tem um perfomance muito boa (um dos motivos na qual o gRPC é bem performatico é que o protocolo é em binario).

Site do gRPC: https://grpc.io/

Modelo do RPC: ![model](https://media.geeksforgeeks.org/wp-content/uploads/operating-system-remote-procedure-call-1.png)

**Comment by LorhanSohaky** [comment]
Entendi. Só tenho algumas dúvidas

- nós trabalhamos como um proxy de serviço de terceiros. E acho que na maioria das vezes só repassamos os dados. De vez em quando temos um processamento em cima do dado. Nessa situação ainda vale a pena transformar o dado em GRPC?
- Usando GRPC não cria mais dificuldade para ler o dado? Uma vez que nós não fornecemos SDKs oficiais
- Teria algum jeito fácil de manter os dois tipos de saída?

**Comment by peeeuzin** [comment]
Boas perguntas, vou tentar responde-las:

 * Usar o gRPC pode aumentar o performance da **transmissão** de dados entre o server e o client.
 * o gRPC já tem algumas libs para algumas linguagens de programação (como Go, C++, Python, Java e etc), porém há também libs não-oficiais do gRPC open-source (como o tonic-rs do Rust).
 * Tem como manter o HTTP e o gRPC sem problemas no servidor.

**Comment by fernandohre** [comment]
2 centavos de opinião.

Faz sentido usar gRPC quando você tem controle de MAIORIA do software porque dependerá de alterações do outro lado também. No caso do BrasilAPI fazemos requisição para muitos serviços de terceiros que na maioria são chamadas REST em protocolo HTTP e não temos controle do outro servidor. Exemplo: Não temos controle do servidor do ViaCEP.

Utilizar gRPC no nosso cenário adicionaria uma complexidade a mais para resultados não significativos.
@peeeuzin Adoraria ver uma prova de conceito para provar que estou errado 😊

**Comment by tiagoassis00** [comment]
@fernandohre: Explicando rapidamente, o ganho do gRPC está na remoção dos nomes dos campos e caracteres auxiliares necessários no JSON e XML. Algo como {"ano": 2023, "mes":08, "dia": 30} viraria 20230830 e em binário 0x07E7,0x08,0x1F.
É a mesma lógica de como uma struck é salva em memória, e da mesma forma, a ordem dos campos se torna obrigatória e a forma de conversão de dados em binário também precisa ser a mesma usada por quem gera e por quem recebe o dado. São essas regras e algoritmos que é o gRPC+Protobuf.
Somando a isso, a API de vocês já é JavaScript então a integração por JsonRPC, ou REST API, continua sendo a melhor para o seu cenário de centralizadores de APIs publicas.

**Comment by cezarmezzalira** [comment]
Adicionando mais 2 cents:
Atualmente, na plataforma que eu trabalho, usamos gRPC apenas para aplicações internas, ou micro serviços. Quando se tem o controle dos contratos de interface, que são os arquivos protobuf, vale muito a pena usar. Porém, como o core da BrasilAPI está em conectar serviços API REST, não faria realmente tanto sentido assim, dado que complexidade de manter seria maior que o ganho em performance.
Acredito que existam outras técnicas melhores que acredito que já devam ser usadas, que é a questão de cache dos dados por algum período para evitar saturar as API's de origem por exemplo.

**Comment by peeeuzin** [comment]
A minha ideia original era usar o gRPC nas bibliotecas do BrasilAPI, para dar mas performance nessas libs.

**Comment by HClausing** [comment]
> A minha ideia original era usar o gRPC nas bibliotecas do BrasilAPI, para dar mas performance nessas libs.

Eu acredito que neste caso o ganho pode ser nulo ou muito pequeno, pela explanação que o @fernandohre menciona que os dados vem de serviços externos, que teoricamente já são consumidos em Http. Se desde a origem dos dados já fosse utilizado o gRPC, aí sim creio que o ganho teria grande relevância.

**Comment by peeeuzin** [comment]
> > A minha ideia original era usar o gRPC nas bibliotecas do BrasilAPI, para dar mas performance nessas libs.
> 
> 
> 
> Eu acredito que neste caso o ganho pode ser nulo ou muito pequeno, pela explanação que o @fernandohre menciona que os dados vem de serviços externos, que teoricamente já são consumidos em Http. Se desde a origem dos dados já fosse utilizado o gRPC, aí sim creio que o ganho teria grande relevância.
> 
> 
> 
> Na prática, penso que só testando lado a lado mesmo para ter um parecer final.

Testei algumas vezes o gRPC e realmente não faz sentido o esforço para o um desempenho mínimo, até porque, como você disse, as informações vem de APIs HTTP, o BrasilAPI só repassa elas.

Vou fechar a issue devido ao motivo citado à cima.

Obrigado por todos que participaram e contribuíram a issue.
