### ISSUE TITLE
[gelocalização errada] - busca cep v2

### ISSUE THREAD

**Issue by WellingtonFonseca** [BrasilAPI/BrasilAPI#439]
pessoal, estou a um tempo trabalhando em uma base dados aqui e notei que as coordenadas retornada por:
https://brasilapi.com.br/api/cep/v2/02917050

está indevida, pelo o que entendi esses dados são puxados do openstreetmap e consultando lá de fato a coordenada que retorna condiz com uma busca do endereço: **Rua Antônio Correia, São Paulo,**
porém não condiz com a localidade que estou procurando. como assim? ao fazer a solicitação no OSM ele me retorna duas localidades 
```
- 1 -
Via residencial 
[Rua Antônio Correia, 
Igarapava, 
Região Imediata de Ituverava, 
Região Geográfica Intermediária de Ribeirão Preto, 
São Paulo, 
Região Sudeste, 
14540-000, Brasil](https://www.openstreetmap.org/way/532596250)
```
```
- 2 -
Via residencial 
[Rua Antônio Correa, 
Vila Pereira Cerca, 
Pirituba, 
São Paulo, 
Região Imediata de São Paulo, 
Região Metropolitana de São Paulo, 
Região Geográfica Intermediária de São Paulo,
São Paulo, Região Sudeste, 
02933-180, Brasil](https://www.openstreetmap.org/way/79877348)
```

a geolocalização retornada via brasilapi é a `- 1 -`, porém a que necessito é da `- 2 -`.
não tem como retornar estes dados acima que informei com as coordenadas e quem estiver consumindo os dados decidir qual usar?

vou tentar montar o repositório aqui na minha máquina para procurar uma solução, mas por hora não consigo. desde já obrigado a todos

**Comment by WellingtonFonseca** [comment]
Incremental, você diz em grande quantidade? Se for, sou eu sim, porque? fiz algo de errado?

**Comment by WellingtonFonseca** [comment]
MEUS DEUS ME PERDOA. Agora que vi essa parte do texto, já vou cancelar o script aqui. ME PERDOA de verdade.


Termos de Uso

O BrasilAPI é uma iniciativa feita de brasileiros para brasileiros, por favor, não abuse deste serviço. Estamos em beta e ainda elaborando os Termos de Uso, mas por enquanto por favor não utilize formas automatizadas para fazer "crawling" dos dados da API. Um exemplo prático disto é um dos maiores provedores de telefonia do Brasil estar revalidando, neste exato momento, todos os Ceps (de 00000000 até 99999999) e estourando em 5 vezes o limite atual da nossa conta no servidor. O volume de consulta dever ter a natureza de uma pessoa real requisitando um determinado dado. E para consultas com um alto volume automatizado, iremos mais para frente fornecer alguma solução, como por exemplo, conseguir fazer o download de toda a base de Ceps em uma única request.

**Comment by WellingtonFonseca** [comment]
olha, de verdade, fiquei chateado comigo aqui. não estou sendo malandro, realmente não sabia do termo de uso.
então estava tentando entender o que de fato houve pra que eu tivesse furado o termo e me recordei que não vim aqui no github diretamente, somente via site (abaixo) e me recordo de ter procurado por lá se havia limitações e como não encontrei algo que mencionava prossegui com um script para fazer a pesquisa em massa que eu precisava.

veja abaixo que em nenhum momento menciona, se tiver como adicionar creio que ajude outros a cometerem o mesmo erro que eu.

novamente, me perdoa.

![image](https://user-images.githubusercontent.com/25608175/203703471-6f88fe3f-b489-4b0d-90da-591b7c8972dc.png)
![image](https://user-images.githubusercontent.com/25608175/203704112-0841b8cc-550f-4ea8-bc7b-eb9412ef2748.png)
![image](https://user-images.githubusercontent.com/25608175/203703506-fdcd92da-fcee-43e2-a4a2-2ed9288ad555.png)

**Comment by LorhanSohaky** [comment]
Bom ponto, é bom colocarmos na documentação algum aviso a respeito disso para evitar usos "abusivos"
