### ISSUE TITLE
Bug: busca de CNPJ com erro 504 Gateway time-out

### ISSUE THREAD

**Issue by C4stro** [BrasilAPI/BrasilAPI#443]
![image](https://user-images.githubusercontent.com/13188009/206473403-4a198851-349a-4fc0-be85-5875a0f03279.png)

A busca de CNPJs não está funcionando atualmente.

**Comment by LorhanSohaky** [comment]
Pata todos os CNPJs ou para algum em específico?

**Comment by C4stro** [comment]
retornou, acredito que fosse apenas instabilidade.
