### ISSUE TITLE
Todos os serviços de CEP retornaram erro.

### ISSUE THREAD

**Issue by cpracideli** [BrasilAPI/BrasilAPI#448]
Olá, ao realizar qualquer requisição nos endpoints de CEP (v1 e v2), o mesmo retorna HTTP 404

`{
    "name": "CepPromiseError",
    "message": "Todos os serviços de CEP retornaram erro.",
    "type": "service_error",
    "errors": [
        {
            "name": "ServiceError",
            "message": "Erro ao se conectar com o serviço dos Correios.",
            "service": "correios"
        },
        {
            "name": "ServiceError",
            "message": "Erro ao se conectar com o serviço ViaCEP.",
            "service": "viacep"
        },
        {
            "name": "ServiceError",
            "message": "Erro ao se conectar com o serviço WideNet.",
            "service": "widenet"
        }
    ]
}`

**Comment by murilohns** [comment]
@cpracideli, qual URL você está acessando?
Está enviando o CEP na URL?

**Comment by lidymonteiro** [comment]
@murilohns estou tendo o mesmo problema. Testei com vários CEP. Tanto na v1 como na v2.

**Comment by santosbio** [comment]
Aqui também parou de funcionar, tanto na v1 quanto na v2.

URLs que testei: 
https://brasilapi.com.br/api/cep/v1/38411336
https://brasilapi.com.br/api/cep/v2/38411336

`{"message":"Todos os serviços de CEP retornaram erro.","type":"service_error","name":"CepPromiseError","errors":[{"name":"ServiceError","message":"Erro ao se conectar com o serviço dos Correios.","service":"correios"},{"name":"ServiceError","message":"Erro ao se conectar com o serviço ViaCEP.","service":"viacep"},{"name":"ServiceError","message":"Erro ao se conectar com o serviço WideNet.","service":"widenet"}]}`

**Comment by lidymonteiro** [comment]
Tem uns voltando a pegar e outros não :/

**Comment by murilohns** [comment]
@lidymonteiro @cpracideli @santosbio @gazillmer podem confirmar se voltou? aparentemente foi uma instabilidade no correios

**Comment by cpracideli** [comment]
@murilohns Aparentemente voltou, fiz o testes em diversos CEPs e tudo ok até o momento. 
Obrigado pelo rapido retorno!

**Comment by lidymonteiro** [comment]
@murilohns voltou! Muito obrigada pelo retorno e rapidez

**Comment by murilohns** [comment]
se quiserem vocês podem se [juntar ao nosso slack](https://github.com/BrasilAPI/BrasilAPI/issues/186)

Lá vocês conseguem marcar eu e o @lucianopf, e conseguimos ver mais rápido as notificações nesses casos de queda / instabilidade

Obrigado pelo retorno :)
