### ISSUE TITLE
Amapá não retorna municípios

### ISSUE THREAD

**Issue by matemora** [BrasilAPI/BrasilAPI#458]
Ao solicitar municípios do amapá, não existe retorno.
![image](https://user-images.githubusercontent.com/56656102/214363349-82a7f106-dd1d-43d6-bcb4-372f77e002a4.png)
Na api do ibge existe resultado:
![image](https://user-images.githubusercontent.com/56656102/214363466-eea2450a-65b3-45d3-871f-542cbac66c7c.png)

Não sei se estou fazendo algo errado, mas poderiam me ajudar?

**Comment by LorhanSohaky** [comment]
Não sei dizer se foi algum caso pontual de cache, mas com [AP em minúsculo](https://brasilapi.com.br/api/ibge/municipios/v1/ap) funcionou

**Comment by matemora** [comment]
Poxa entendi. Acredito que pra manter a consistência seria legal se funcionasse com as duas opções. Por exm, SP (maiúsculo) funciona. Devo abrir uma nova issue para isso?

**Comment by RodriAndreotti** [comment]
@LorhanSohaky, Testando aqui acho é o mesmo caso que aconteceu comigo naquela outra vez e que subi o PR https://github.com/BrasilAPI/BrasilAPI/pull/410 para corrigir.

@matemora, tenta passar no url uma lista de providers de onde vc quer buscar, pois se ele estiver buscando na Wiki e a lista de lá estiver zoada, dá esse problema.

exemplo de request com os providers:

`https://brasilapi.com.br/api/ibge/municipios/v1/AP?providers=gov,dados-abertos-br`

**Comment by LorhanSohaky** [comment]
@RodriAndreotti , tens razão. O problema é este mesmo; estou avaliando se não é melhor remover a wikipedia ou criar uma blacklist pra ela

**Comment by matemora** [comment]
Ta certo pessoal, obrigado pelo retorno de vcs. Acho que por hora, minha dúvida está sanada.
