### ISSUE TITLE
SDK para PHP

### ISSUE THREAD

**Issue by carloscarucce** [BrasilAPI/BrasilAPI#471]
Olá. Na ultima semana estive trabalhando em uma biblioteca para o PHP.
Ainda falta concluir a documentação mas todos os endpoints da release atual já são suportados. 

Quando concluir essa documentação, como posso fazer para ser incluído na lista de bibliotecas da comunidade?

Segue a url do repositório: https://github.com/Corviz/brasilapi-php

**Comment by RodriAndreotti** [comment]
Chegou primeiro que o meu... kkkk
Mas é bem tranquilo, mano.

Faz um fork do repo, atualiza o readme com o link e faz o PR.

**Comment by carloscarucce** [comment]
Show! Obrigado!
