### ISSUE TITLE
Bug na api de bancos

### ISSUE THREAD

**Issue by ian-rafael** [BrasilAPI/BrasilAPI#476]
Alguns bancos estão aparecendo com aspas nos campos. A formatação do csv (`formatCsvFile` em `services/banco-central/index.js`), não está tratando colunas que estão entre aspas (aspas porque a coluna possui vírgula).

Por exemplo:
csv
```csv
36947229,COBUCCIO S.A. SCFI,402,Não,RSFN,"COBUCCIO S/A - SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTOS",03/12/2020
```
json
```json
{"ispb":"36947229","name":"COBUCCIO S.A. SCFI","code":402,"fullName":"\"COBUCCIO S/A - SOCIEDADE DE CRÉDITO"}
```

**Comment by walissonhms** [comment]
Pelo que vi o problema não está na vírgula (,) e sim na contra barra (\)

**Comment by RodriAndreotti** [comment]
Boa tarde, @ian-rafael!
Cara, realmente havia um bug ai, acabei de subir um fix, assim que aprovarem o PR deve ficar OK
