### ISSUE TITLE
Dados de CNPJ desatualizados

### ISSUE THREAD

**Issue by Ceagah** [BrasilAPI/BrasilAPI#483]
Fala pessoal ! Beleza ? 
Gente, eu estou utilizando a Api para consultas, e percebi que ela está desatualizada .
Ao consultar o Cnpj de numero `42352688000119` , que foi baixada em Janeiro. E a situação dela na Brasil Api ela ainda consta em aberto. 

![image](https://user-images.githubusercontent.com/40706788/230411535-8ed345a7-5b94-4c67-8548-9d48de256752.png)

![image](https://user-images.githubusercontent.com/40706788/230411669-f1822d7c-a769-4a00-aafa-1e0a5cbd4478.png)

**Comment by LorhanSohaky** [comment]
Olá @Ceagah . Sob esse quesito não temos controle. A nossa fonte de dados é a [minhareceita](https://docs.minhareceita.org/) que é de fonte tiramos a informação.

Acho que existem duas possibilidades para o corrido

1. A receita federal ainda não disponibilizou os zips para que os dados sejam atualizados
2. A Minha Receita está em período de atualização
3. Ocorreu algum erro ao atualizar os dados no lado deles

@cuducos , sabe dizer?

**Comment by cuducos** [comment]
> sabe dizer?

[Sei](https://github.com/cuducos/minha-receita/issues/175).

**Comment by juliozeneg** [comment]
Oi @Ceagah, tudo bem?
Conseguiu resolver, essa parte da consulta CNPJ?
