### ISSUE TITLE
Erro 500

### ISSUE THREAD

**Issue by geisimarrech87** [BrasilAPI/BrasilAPI#485]
Olá.
Tentando usar essa API em meu App, mas tem um CEP com problemas.

https://brasilapi.com.br/api/cep/v2/78891076
![Captura de Tela 2023-04-24 às 11 10 22](https://user-images.githubusercontent.com/48284042/234039782-6e7aa1f5-9ee0-4093-b438-f2d0fb948127.png)
<img width="849" alt="Captura de Tela 2023-04-24 às 11 11 08" src="https://user-images.githubusercontent.com/48284042/234039789-4b911ee5-b010-4aad-b42b-3017dd67c8fc.png">

**Comment by vini-se** [comment]
Querido, provavelmente você fez muitas requisições e o serviço parou de responder, aconteceu algumas vezes comigo, mas, na minha máquina está funcionando normalmente, segue print: 
![image](https://user-images.githubusercontent.com/70918792/234159998-a1ae39a0-15b8-4ea5-9d98-d6c029ca76bb.png)

(Antes que pergunte, para visualizar o JSON desse jeito, estou usando uma extensão do Chrome, JSON Viewer)

**Comment by geisimarrech87** [comment]
@vini-se 
Só se o serviço conta requisições por CEP, porque no mesmo momento que consultei este CEP com erro, outros funcionavam. 
As vezes ele funciona, as vezes da erro.

Eu sei que o serviço usa como redundância o viacep, mas acabei fazendo isso no meu app também. A princípio funciona.

**Comment by geisimarrech87** [comment]
Outra possibilidade, se o problema é o grande número de requisições, seria retornar uma mensagem de erro específica.

**Comment by murilohns** [comment]
@geisimarrech87 aparentemente foi um problema de intemitência nos provedores de CEP.

A API já estabilizou pra você?

**Comment by geisimarrech87** [comment]
@murilohns aparentemente está normal agora.

**Comment by LorhanSohaky** [comment]
@murilohns , conseguimos descobrir o que exatamente falhou? Se foi algum provedor do cep ou a parte de geolocalização?

**Comment by guilhermepv** [comment]
em 2 sites diferentes, a api esta com problema?

Acess to XMLHttpRequest at 'https://brasilapi.com.br/api/cep/v1/19061070?_tutor_nonce=88779b6805' from origin 'https://meusite.com.br' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by LorhanSohaky** [comment]
@guilhermepv , o problema é só com a cep v1? Pode testar com outros endpoints?

**Comment by guilhermepv** [comment]
@LorhanSohaky funcionou na v2! obrigado.

acho que outras pessoas podem estar com o mesmo problema pq utilizo ele em um plugin de wordpress: https://wordpress.org/plugins/autocomplete-address-for-woocommerce/

para quem quiser trocar basta alterar o arquivo /wp-content/plugins/autocomplete-address-for-woocommerce/assets/js/autocomplete-address.4dd81181ce7c15cd78b1.js

ajax({type:"GET",url:"https://brasilapi.com.br/api/cep/**v2**/".concat(c)

**Comment by alphavaletec** [comment]
Para mim também está aparecendo o mesmo erro: Ensure CORS response header values are valid
Porém, quando é feito a consulta direta na URL, a API funciona bem!

O plugin para preenchimento do CEP é muito útil!

Se eu pudesse ajudaria, mas não tenho conhecimento!

Ofereço uma doação de algum valor se for ajudar!

**Comment by yazaldefilimonepinto** [comment]
@alphavaletec  ainda com o problema? se percebe voce quer uma solucao no plugin do wordpress?

**Comment by alphavaletec** [comment]
> @alphavaletec ainda com o problema? se percebe voce quer uma solucao no plugin do wordpress?

Ja foi resolvido! Muito obrigado!

**Comment by ZCErik** [comment]
Se @geisimarrech87 já resolveu, podemos fechar o issue?

**Comment by geisimarrech87** [comment]
@ZCErik pode fechar. Obrigado pela ajuda.
