### ISSUE TITLE
Endpoint /api/cep/v2/{cep}

### ISSUE THREAD

**Issue by ormenese** [BrasilAPI/BrasilAPI#487]
O endpoint /api/cep/v2/{cep} está retornando {} para qualquer CEP.

**Comment by lucianopf** [comment]
Mestre, pode pfv detalhar um pouco mais o que tá rolando por aí?
Validei aqui e parece estar funcionando corretamente 👀 

https://brasilapi.com.br/api/cep/v2/29090200

**Comment by ormenese** [comment]
Desculpe, não são todos os CEP´s !!!
Mas alguns do estado de SP que precisei fazer busca.

https://brasilapi.com.br/api/cep/v2/13432033
{}

https://brasilapi.com.br/api/cep/v2/13058177
{}

Testando no endpoint V1 vai de boa.

https://brasilapi.com.br/api/cep/v1/13432033
{"cep":"13432033","state":"SP","city":"Piracicaba","neighborhood":"Centro (Ártemis)","street":"Rua Quinze de Novembro","service":"correios"}

https://brasilapi.com.br/api/cep/v1/13058177
{"cep":"13058177","state":"SP","city":"Campinas","neighborhood":"Jardim Bassoli","street":"Rua Quinze","service":"correios"}

**Comment by danilo-teixeira** [comment]
Olá.
Também estou enfrentando o mesmo problema com o CEP `18020216`. Retornava normalmente utilizando a API V2, mas agora está retornando somente `{}`. Utilizando a API V1 retorna os dados normalmemte.

**Comment by wisliy** [comment]
Mesmo problema aqui. Até então nunca tinha recebido esse retorno `{}`
Exemplo:

https://brasilapi.com.br/api/cep/v2/65633626
 `{}`

Já no /v1 os dados do CEP são retornados com sucesso:
https://brasilapi.com.br/api/cep/v1/65633626
`{
cep: "65633626",
state: "MA",
city: "Timon",
neighborhood: "Cidade Nova",
street: "Rua Treze",
service: "correios"
}`

**Comment by lucianopf** [comment]
Galera mil perdões pela lentidão de ver essa issue 😢 
De fato estamos com um problema na v2 em especial na consulta de geolocalização dos CEPs.

Já identifiquei o que foi alterado e criei um PR para essa correção, logo logo isso deve estar normalizado.

Perdão pela demora =/

https://github.com/BrasilAPI/BrasilAPI/pull/490

**Comment by lucianopf** [comment]
Merge feito e comportamento corrigido! 🚀

**Comment by Nela62** [comment]
Olá,
Estou tendo o mesmo problema. A API não retorna as coordenadas. Apenas recebo um object vazio {}. 

Por examplo, 
https://brasilapi.com.br/api/cep/v2/13432033
https://brasilapi.com.br/api/cep/v2/89010025

<img width="345" alt="Screenshot 2023-07-06 at 9 12 49 PM" src="https://github.com/BrasilAPI/BrasilAPI/assets/12697777/cb938159-79ac-4bee-a52d-88ba208df57e">
