### ISSUE TITLE
[discussão] Typescript?

### ISSUE THREAD

**Issue by WeslleyNasRocha** [BrasilAPI/BrasilAPI#49]
Seria legal usar typescript no projeto não?

**Comment by lucianopf** [comment]
Quase que de 3 em 3 meses me forço a criar projetos usando Typescript pra me convencer que o overhead faz sentido mas sempre acabo com a mesma sensação.. =/
Sempre me pego no final com uma falsa sensação de ser super produtivo e com o código super seguro, só que na verdade, o mesmo projeto em JS puro com os mesmos cuidados tomados teriam a mesma segurança e provavelmente num tempo menor.

O tooling que o TS traz é sensacional, o VSCode por exemplo vira uma belezura!! (apesar que o VSCode sempre usa o interpretador do TS pra poder ajudar nas sugestões, inclusive no JS puro) 

Com essas impressões quero levantar a discussão sobre as percepções suas e de outras pessoas. 😬

Como eu disse, eu frequentemente me pego fazendo esses testes, e se fosse escolhido escrever TS aqui faria também com alegria! ^^

**Comment by akinncar** [comment]
Ainda não sou total adepto do TypeScript, mas volta e meia encontro issues desse tipo nos mais diversos repositórios open source. O fato é que atualmente, não vejo uma necessidade de fato de ter de modificar um projeto inteiro (mesmo sendo em partes, e aos poucos) para inserir o typescript. Há outras necessidades e sugestões que estão sendo apontadas na issues, que vejo como sendo mais relevantes para a melhoria do projeto.

É claro que é muito excitante ver diversos novos projetos sendo criados em TypeScript e quase que toda comunidade apontando isso como o futuro do Javascript, mas como mencionado pelo @lucianopf acima, um projeto bem escrito com JS pode entregar a mesma experiencia de código legível e produtivo quanto a um desenvolvido com TS.

Dito isso, também gostaria de saber a opinião dos demais, e outros pontos de vista sobre esse assunto.

**Comment by estevam31** [comment]
Opa, sou novo por aqui e fiquei muito empolgado em contribuir com um projeto tão massa!

Logo de cara minha primeira dúvida foi o fato de o projeto estar utilizando javascript puro mesmo com o Next.js tendo suporte ao [typescript "out of the box"](https://nextjs.org/docs/basic-features/typescript)...

Minha visão é que hoje TS é uma tendência muito forte que tem tudo pra se tornar o default dos projetos Javascript, considerando que:

* **O feedback loop diminui drasticamente**.
* Código Typescript é self-documenting, em um projeto que tem tudo pra ter uma codebase gigante como esse, a tipagem estática pode ajudar muito na estrutura do código e na chegada de novos contribuidores.
* Apesar de ser subjetivo, um projeto escrito em Typescript bem configurado pode levar a uma experiência de desenvolvimento muito mais fluída e segura graças ao Intellisense integrado do VSCode e outras IDEs.

Considerando que esse é um projeto novo, migrar para Typescript agora não seria uma dor tão grande, eu mesmo poderia ser atribuido dessa tarefa, porém, quando a codebase crescer isso pode se tornar um grande problema.

Um exemplo básico que o Typescript pode ajudar com novos contribuidores é a `request` e `response` do Next.js ou os resolvers de GraphQL:

```typescript
async function Cep(request: NextApiRequest, response: NextApiResponse): void 
```

Tipando os parâmetros o desenvolvedor conseguiria ter controle de todos os métodos públicos dos mesmos, dessa forma facilitando tanto pra que já sabe codar em Javascript quanto para novos contribuidores.

Concordo sim que o processo de setup do Typescript pode ser bem chato, e mesmo utilizar o `strictMode` pode causar certa lentidão no processo de desenvolvimento, porém, em contra-partida torna a codebase muito mais sólida.

Hoje eu utilizo Typescript em praticamente todos os meus projetos e isso vem me facilitando bastante a vida então posso estar com a visão enviesada, por isso, também gostaria muito que a galera compartilhasse sua visão sobre o assunto.

**Comment by AcidTr** [comment]
Estou em um projeto de migrar um App Ionic v1 para react-native e já estou fazendo o refactor para Typescript, porque lembrei que o projeto antigo passou muita gente e muita gente não sabia como funcionava o projeto(os métodos, as classes, os services). Isso gerou um código absurdamente grande e complicado de dar a devida manutenção com métodos repetidos para a mesma coisa praticamente. Com o Typescript eu já estou pensando em evitar esse problemão. Então acho válido como o @estevam31 comentou acima que isso vai ajudar a novos contribuidores ao projeto ter um código que já sugira os métodos que pode ser utilizado.

**Comment by filipedeschamps** [comment]
Fala pessoal! Coloquei minha opinião lá no Pull Request: https://github.com/filipedeschamps/BrasilAPI/pull/69

🤝
