### ISSUE TITLE
Woocomerce

### ISSUE THREAD

**Issue by b2ubank** [BrasilAPI/BrasilAPI#497]
Tem como integrar com woocommerce?

Para quem quiser aproveitar:

Olá! 👍API bancária que faz Pix, consulta saldo e etc para desenvolvedores. Sem taxa alguma e suporte por WhatsApp.

https://apidoc.b2ubank.com/

PJ e PF, ambos sem limites de transferência. 

Ótima para integrar no seu software. 😏

**Comment by Muurilo** [comment]
Um pouco sugestiva sua issue, parece mais uma propaganda!

**Comment by RodriAndreotti** [comment]
> Um pouco sugestiva sua issue, parece mais uma propaganda!

Também conhecido como spam

**Comment by doardin** [comment]
> Um pouco sugestiva sua issue, parece mais uma propaganda!

Realmente é uma propaganda hahaahha

**Comment by fyosetake** [comment]
> > Um pouco sugestiva sua issue, parece mais uma propaganda!
> 
> Realmente é uma propaganda hahaahha

Tem até o 'link', se bobear cai no 'checkout'.

**Comment by danielbecher** [comment]
Mas que seria interessante que os bancos liberassem uma APIzinha, seria... hehehe.

**Comment by RodriAndreotti** [comment]
> Mas que seria interessante que os bancos liberassem uma APIzinha, seria... hehehe.

Mas a maioria deles tem API para pix (se não todos, visto que é algo que vem do Banco Central), alguns disponibilizam na api tbm boletos, saldo etc.

Inclusive tem até um repositório do Bacen aqui no github com as especificações da api:
https://github.com/bacen/pix-api

**Comment by b2ubank** [comment]
Seu CNPJ já integrou alguma Api de pix e já fez mais de 1 milhão de transação ou só teoria mesmo?

**Comment by RodriAndreotti** [comment]
Spam
