### ISSUE TITLE
Sugestão: adicionar utilitários nacionais

### ISSUE THREAD

**Issue by giovanifranz** [BrasilAPI/BrasilAPI#500]
Na maioria das aplicações que atuei até o momento é sempre necessário fazer as mesmas validações que poderiam estar centralizadas nessa mesma API.

Alguns exemplos: 
isValidCPF
formatCPF
generateCPF

isValidCNPJ
formatCNPJ
generateCNPJ

isValidCEP
formatCEP

isValidPIS
isValidBoleto
isValidEmail
isValidPhone

formatCurrency
parseCurrency

getStates
getCities
capitalize

**Comment by doardin** [comment]
Eai Giovani, tudo bem?

Queria primeiramente agradecer pela sua ideia, mas preciso levantar alguns pontos em relação a ela.

Primeiro de tudo, é que o seu problema de reescrever código pode ser resolvido com a criação de pacotes utilitários para realizar essas validações. Alguns serviços, como Maven, npm e pip, podem ajudar você a publicar esses códigos para serem reutilizados em outros projetos.

O segundo ponto é que disponibilizar esse tipo de validação em uma API poderia acarretar em vários problemas para ambos os lados (cliente e servidor), como o aumento dos custos de processamento do servidor, o aumento da latência de respostas (tanto para o cliente quanto para o servidor). Além disso, vale ressaltar que a API poderia ficar sobrecarregada de requisições, uma vez que inúmeras pessoas passariam a usar esse serviço.

Outro ponto importante é que é muito mais custoso para um servidor fazer uma requisição externa para realizar essas validações do que realizar a validação localmente.


att, 
Eduardo Lopes.
