### ISSUE TITLE
CEP V2 - invalid json response body at https://nominatim.openstreetmap.org/search/?...

### ISSUE THREAD

**Issue by wisliy** [BrasilAPI/BrasilAPI#505]
Olá!

A API de CEP V2 está retornando erro ao tentar consultar um CEP.
`https://brasilapi.com.br/api/cep/v2/88025000`

```
{
  "message": "invalid json response body at https://nominatim.openstreetmap.org/search/?format=json&addressdetails=1&country=Brasil&state=SC&city=Florian%C3%B3polis&street=Rua%20Frei%20Caneca%20-%20at%C3%A9%20338/339 reason: Unexpected token < in JSON at position 0",
  "type": "invalid-json"
}
```

![image](https://github.com/BrasilAPI/BrasilAPI/assets/23408622/06fc3117-155f-4bf7-b1df-38c9c79cf2be)

Se tentar acessar a URL mencionada na mensagem, ocorre o seguinte erro:

![image](https://github.com/BrasilAPI/BrasilAPI/assets/23408622/42c03588-eaa0-4a18-97a8-201a2285c9c9)

A consulta pela API V1 funciona com sucesso.

`https://brasilapi.com.br/api/cep/v1/88025000`

**Comment by theusmoreira** [comment]
Tem uma PR aberta #504 para isso.

**Comment by LorhanSohaky** [comment]
Resolvido
