### ISSUE TITLE
Padronização response api /taxas

### ISSUE THREAD

**Issue by vhs94** [BrasilAPI/BrasilAPI#510]
- [api/taxas/v1](https://brasilapi.com.br/api/taxas/v1) retorna SELIC como Selic
- [api/taxas/v1/selic](https://brasilapi.com.br/api/taxas/v1/selic) retorna tudo toUpper

... no código: 

![image](https://github.com/BrasilAPI/BrasilAPI/assets/6922181/8d08dbb2-239c-4705-bfd9-780744c55dcf)

Parece facil, se me sobrar um tempinho eu msm posso ajudar, ou se alguém fizer antes maneiro :)

acho que deveria começar a haver alguma preocupação com essas padronizações, principalmente na língua usada. isso tá refletindo nos client-sdk's que estao ficando tudo em pt/ingles misturado hehe

**Comment by RodriAndreotti** [comment]
Opa... na realidade tem um PR em discussão sobre algumas coisas referentes a padronização aqui, porém precisamos discutir realmente alguns pontos para publicá-lo https://github.com/BrasilAPI/BrasilAPI/pull/268 .
O complicado é que nos endpoints que já existem não temos como mudar, pois quebrará as integrações que já utilizam.

O Ideal é criar uma v2 de cada endpoint com tudo padronizado e ai, conforme o uso da v2 for aumentando e a v1 diminuindo matamos tudo da v1.

**Comment by vhs94** [comment]
top mano! que legal que ja tem algo nesse sentido, vou acompanhar.
