### ISSUE TITLE
Api CPTEC de busca de cidade pelo nome retorna erro quando se passa o nome completo da cidade

### ISSUE THREAD

**Issue by ElderBarbosaLima** [BrasilAPI/BrasilAPI#514]
Ao chamar o endpoint https://brasilapi.com.br/api/cptec/v1/cidade/Belo Horizonte com o nome da cidade completo (ex: Belo Horizonte) a api retorna o erro
`{
    "message": "Erro ao buscar informações sobre cidade",
    "type": "city_error",
    "name": "CITY_INTERNAL"
}`
mas se a busca for realizada com apenas parte do nome possibilitando que a busca encontre mais de um registro, o registro 'Belo Horizonte' é encontrado: 
endpoint: https://brasilapi.com.br/api/cptec/v1/cidade/Belo
retorno: `[
    {
        "nome": "Belo Campo",
        "id": 829,
        "estado": "BA"
    },
    {
        "nome": "Belo Horizonte",
        "id": 222,
        "estado": "MG"
    },
    {
        "nome": "Belo Jardim",
        "id": 830,
        "estado": "PE"
    },
    {
        "nome": "Belo Monte",
        "id": 831,
        "estado": "AL"
    },
    {
        "nome": "Belo Oriente",
        "id": 832,
        "estado": "MG"
    },
    {
        "nome": "Belo Vale",
        "id": 833,
        "estado": "MG"
    }
]` 
O erro ocorre mesmo se nome da cidade não contenha caracteres especiais ou espaços. Identificado que para alguns casos a api funciona como esperado ao chamar pelo nome de cidade 'São Paulo'

**Comment by RodriAndreotti** [comment]
Buenas, @ElderBarbosaLima!
Vou dar uma olhada nesse comportamento.

**Comment by RodriAndreotti** [comment]
@ElderBarbosaLima, obrigado por reportar o bug.
Acabou de subir um ajuste para ele, logo que o PR for aprovado não devemos ter outro problema com isso.
Adicionei também um teste automatizado, para garantir que no futuro não quebre novamente.
