### ISSUE TITLE
Retorno 'undefined' quando informação 'não se aplica' (N/A)

### ISSUE THREAD

**Issue by fyosetake** [BrasilAPI/BrasilAPI#519]
Moro em uma cidade no interior do estado do Paraná e aqui temos apenas um CEP para todos os logradouros. Quando é buscado o CEP daqui via 'cep-promise', temos retorno 'undefined' para algumas informações:

![cep-promise_unidefined_attributes](https://github.com/BrasilAPI/BrasilAPI/assets/108588170/096bc610-6242-490b-9233-34071f73bac1)

O 'undefined' pode sugerir (enviesadamente) alguma falha na obtenção destas informações, não acham? 

Seria interessante tratar estas ocorrências como 'não se aplica' ou 'não disponível' (N/A ou N/D)? Eu poderia sugerir um 'N/A', o que acham disto?

**Comment by RodriAndreotti** [comment]
Eu sugeriria até mesmo uma string vazia, visto que, teoricamente, essas informações seriam complementadas pelo usuário, e ter um N/D ou N/A seria um texto para ser excluído manualmente ou ser tratado via código.

**Comment by fyosetake** [comment]
> Eu sugeriria até mesmo uma string vazia, visto que, teoricamente, essas informações seriam complementadas pelo usuário, e ter um N/D ou N/A seria um texto para ser excluído manualmente ou ser tratado via código.
> 
> Porém isso acontece na lib cep-promise ou na API do Brasil API?, porque se for na lib acho que o ideal é que o issue estivesse no repositório dela.

Realmente, até porque não é lógico garantir que 'undefined' seja sempre 'N/A' ou 'N/D'.

Quanto ao local adequado desta 'issue', você tem razão! Vou 'fechar' esta e abrir outra lá!
