### ISSUE TITLE
CEP sem geolocalização

### ISSUE THREAD

**Issue by soutowhs** [BrasilAPI/BrasilAPI#523]
Possuo um CEP (`35572032`) onde nao eh retornado as coordenadas

<img width="1267" alt="image" src="https://github.com/BrasilAPI/BrasilAPI/assets/65272797/87f8c9a4-76b1-4e74-a756-c48beebe55d2">

nesses casos, isso eh um problema onde nos mesmos conseguimos resolver? Como o [CepAberto](https://www.cepaberto.com/) onde eh possivel contribuir adicionando informações para locais que estão desatualizados/incompletos

**Comment by marciocaimes** [comment]
@soutowhs vi que meu CEP também não tinha as coordenadas. Vi no código que esses dados são obtidos do [openstreetmap](https://www.openstreetmap.org). Fiz uma controbuíção lá, corrigindo o CEP do meu endereço. Agora as coordenadas passaram a vir.

**Comment by icaromourao** [comment]
@soutowhs  no aqruivo "\BrasilAPI\pages\docs\doc\cep.json" existe a seguinte "mensagem":

```javascript
{
  "name": "CEP V2",
  "description": "A geolocalização dos CEPs estão suscetíveis a erros, pois as coordenadas são provindas do OpenStreetMap. Caso encontre algum erro você poderá corrigir no próprio OpenStreetMap que será refletido no CEP V2."
}
``` 

Daí vale o que o @marciocaimes disse mesmo. Se quiser arrumar as coordenadas do seu CEP teria que fazê-lo pelo OpenStreetMap :)
