### ISSUE TITLE
Unit and e2e tests

### ISSUE THREAD

**Issue by Khevinn** [BrasilAPI/BrasilAPI#534]
Têm vários testes quebrados, estou tentando subir uma alteração, mas não estou conseguindo. Assim que baixei o projeto e executei os testes, alguns deles quebraram.

**Comment by wellwelwel** [comment]
Fala, @Khevinn 🙋🏻‍♂️

Por ser um test que depende de várias requisições externas, infelizmente é super comum os testes terem falhas que não estão diretamente relacionadas ao código interno.

Os testes que mais costumam falhar são os `fipe-v1.test.js` e `previsao-v1.test.js`, devido a quantidade de requisições e as restrições dessas APIs externas.

Para contornar isso, uma forma super simples seria acrescentar um atraso antes de iniciar as requisições recorrentes para uma mesma API, por exemplo:

```js
export const waitFor = (ms) => new Promise(resolve => setTimeout(resolve, ms));
```

Então:
```js
describe('/fipe/marcas/v1 (E2E)', () => {
  // Aguarda um segundo antes de iniciar a requisição
  beforeEach(async () => await waitFor(1000));
  test('Utilizando sem informar nenhuma tabela de referência', async () => {
    // ...
  });
});
```

---

Fazendo isso, a gente previne a sobrecarga de requisições na API externa e olha só:

<img width="375" alt="Screenshot 2023-11-02 at 02 41 10" src="https://github.com/BrasilAPI/BrasilAPI/assets/46850407/b5981a69-1a6b-4ca0-a1fc-f7e93306f057">

🧙🏻✨

**Comment by wellwelwel** [comment]
@Khevinn, aliás, esses testes que rodei (*print*) foram a partir do seu PR #533 ✨

**Comment by Khevinn** [comment]
Show, muito obrigado mano, vou incluir isso no teste do meu PR
