### ISSUE TITLE
Erro 500 na API de CEP V2 ao realizar consulta

### ISSUE THREAD

**Issue by Suiam** [BrasilAPI/BrasilAPI#538]
Descrição:
Ao realizar uma consulta na API Brasileira de CEP V2 tenho recebido uma resposta de erro 500 (Internal Server Error). 

![image](https://github.com/BrasilAPI/BrasilAPI/assets/10928221/26c215ca-ae85-458e-bd33-a739cd0afb22)

**Comment by arcanjo96** [comment]
Também estou recebendo o mesmo
![image](https://github.com/BrasilAPI/BrasilAPI/assets/22194984/0771005b-469b-4d26-8734-d854b4775ae4)

**Comment by marciotisouza** [comment]
Bom dia, o erro persiste !!!!

**Comment by RafaelBini** [comment]
Bom dia!! Esse erro é muito grave!! Todos as requisições estão falhando na V2 desta forma

**Comment by dragolemx** [comment]
Alguém precisa corrigir isso !!! 😭 😭  Está impactando meus clientes

**Comment by CauanCabral** [comment]
Testando o código localmente não parece ser um problema de implementação, meu palpite é que o openstreetmap esteja bloqueando as requisições.

![image](https://github.com/BrasilAPI/BrasilAPI/assets/83092/dbb88abf-086f-4c07-9adb-12b228ba6d7d)

Inclusive o próprio erro que aparece ao chamar a BrasilAPI contém um link do openstreetmap que abre corretamente o json esperado quando chamado no navegador

![image](https://github.com/BrasilAPI/BrasilAPI/assets/83092/c7bfad93-4ff4-428b-ae7b-cc659883be95)

Uma possível solução seria garantir que caso a API de coordenadas esteja indisponível, pelo menos os dados do CEP retornem (algo que já é tratado em alguns casos):

![image](https://github.com/BrasilAPI/BrasilAPI/assets/83092/91b56e68-12da-4fbd-83d2-516b2c806f33)

**Comment by marciotisouza** [comment]
A V1 está funcionando, não sei se ajuda !

**Comment by diegoatwa** [comment]
Estou usando @BrasilAPI em formulários de cadastro para preencher automaticamente alguns campos, consultar `v1` se `v2` der erro funcionou pra mim, obrigado @marciotisouza.

```js
response = await fetch(`https://brasilapi.com.br/api/cep/v2/${value}`)
if (!response.ok) response = await fetch(`https://brasilapi.com.br/api/cep/v1/${value}`)
```

Quero observar que os [termos de uso](https://brasilapi.com.br/#termos-de-uso) dizem: **Estamos em beta**.

**Comment by RodriAndreotti** [comment]
Outro detalhe que acho interessante mencionar, o openstreetmap tem um limite bastante estrito de requisições:
1 por segundo, então, dependendo da quantidade de requests que tenhamos feito existe a possibilidade de nosso IP ter sido bloqueado :-/

Por esse motivo ainda estamos em Beta, porque não sabemos como se desenrolaria em um cenário com mais usuários simultâneos.

**Comment by victorhdchagas** [comment]
Tem alguma forma de dar Watch nessa issue? rs
Fiz uma gambi, a quem interessar, segue código
```ts

	static async getCep(cep:string){
        
		const response = await fetch("https://brasilapi.com.br/api/cep/v2/"+cep,{
			method:"GET",
			headers:{
				"Content-Type":"application/json"
			}
		})
		const json = await response.json();
		const response2 = await fetch(json.message.substring(json.message.indexOf("https"),json.message.indexOf("reason")-1),{
			method:"GET",
			headers:{
				"Content-Type":"application/json"
			}})
		return await response2.json();
	}
```

**Comment by diegoatwa** [comment]
@victorhdchagas você pode usar a api do GitHub para monitorar o status de uma inssue.

```js
const user = "BrasilAPI"
const repository = "BrasilAPI"
const inssue = "538"

const response = await fetch(`https://api.github.com/repos/${user}/${repository}/issues/${inssue}`)
const data = await response.json()
console.log(data.state) // Can be one of: open, closed, all
```

Documentação: [API Github - Inssues](https://docs.github.com/en/rest/issues)

**Comment by g4rcez** [comment]
> @victorhdchagas você pode usar a api do GitHub para monitorar o status de uma inssue.
> 
> ```js
> const user = "BrasilAPI"
> const repository = "BrasilAPI"
> const inssue = "538"
> 
> const response = await fetch(`https://api.github.com/repos/${user}/${repository}/issues/${inssue}`)
> const data = await response.json()
> console.log(data.state) // Can be one of: open, closed, all
> ```
> 
> Documentação: [API Github - Inssues](https://docs.github.com/en/rest/issues)

Pode usar o github CLI também 

```bash
gh issue view https://github.com/BrasilAPI/BrasilAPI/issues/538
```

**Comment by lucianopf** [comment]
Eita galera, perdão a demora!
Estou olhando pra isso e estamos discutindo sobre como prosseguir com essa rota que recorrentemente tem apresentado alguns problemas =(

**Comment by lucianopf** [comment]
Primeiramente perdão pelo incoveniente galera mas infelizmente dado o abuso de algumas outras pessoas fazendo varredura de ceps nessa rota fomos bloqueados e estamos sempre correndo atrás de bloquear esses possíveis ataques.

Estamos discutindo sobre o futuro dessa rota em especial sobre talvez separar a consulta de CEP (como é na v1) da consulta da geolocalização em outro recurso mas pra isso teremos quebra de interface e infelizmente não é uma decisão trivial.

Inclusive reajam pfv nessa msg com o emoji :world_map: se vcs usam a info de geo dessa rota sempre ou :mailbox: se vcs usam essa rota principalmente pra pegar informações exclusivas sobre a resolução do cep sem a geolocalização. :pray: 

Por hora fomos desbloqueados mas esse problema infelizmente pode voltar a acontecer nessa rota e se tornar a acontecer e vcs não usam o dado de geolocalização eu sugiro migrarem pra v1 que é bem mais estável =/

Muito obrigado a todos nessa thread sobretudo @Suiam @CauanCabral @marciotisouza @diegoatwa e sempre aos queridos @RodriAndreotti e @LorhanSohaky :heart: por toda ajuda!

![image](https://github.com/BrasilAPI/BrasilAPI/assets/8251208/b024113f-eb42-4ece-ab3b-d3eb5ebf7c2c)

**Comment by cfuent-es** [comment]
Olá @lucianopf , obrigado pelo retorno. Vocês acham muito complicado usar autenticação para limitar o pessoal que abusa?

Um problema que eu já tive foi ser bloqueado por ter consultado a API para um mesmo CEP muitas vezes. Cidades pequenas tem um CEP para toda a cidade. Vou desenvolver um banco local para consultar antes de consultar a API, se eu já tiver lá está ok, e não sobrecarrego aqui.

Abraços

**Comment by LorhanSohaky** [comment]
@cfuent-es , você precisa da geolocalização (lat, lng)?

**Comment by murilohns** [comment]
[OFF TOPIC] @Suiam @arcanjo96 @marciotisouza @RafaelBini @dragolemx @CauanCabral @diegoatwa @victorhdchagas @g4rcez @cfuent-es 

Nem sempre estamos olhando Github, e o suporte por lá pode ser mais rápido

[Junte-se ao nosso slack](https://github.com/BrasilAPI/BrasilAPI/issues/186)

**Comment by renansantos** [comment]
Esse CEP tb dá erro 500:
https://brasilapi.com.br/api/cep/v2/15520000

**Comment by GabrielLasso** [comment]
A issue ainda acontece aqui, e ao acessar o link do OSM da mensagem de erro eu tenho um JSON válido.

Caso seja o OSM bloqueando o BrasilAPI,  tem como ver qual a mensagem de erro?
