### ISSUE TITLE
projeto tá ativo?

### ISSUE THREAD

**Issue by nichdemos** [BrasilAPI/BrasilAPI#568]
Oi galera do @BrasilAPI, como tão?

Alguém está fazendo a manutenção desse projeto? tem algumas respostas que estão vazias. Quem mantém o repo em modo de funcionamento? se está funcionando, como posso ajudar?

**Comment by LorhanSohaky** [comment]
@ThiagoNelsi , está sim. A única questão é que o projeto é colaborativo, todos contribuem como podem em seus tempos livres
