### ISSUE TITLE
Campo CNPJ diferente da documentação

### ISSUE THREAD

**Issue by diogoko** [BrasilAPI/BrasilAPI#577]
Na documentação o tipo de logradouro é listado como `descricao_tipo_logradouro`, mas a resposta real ao consultar a API traz esse campo como `descricao_tipo_de_logradouro`.

Posso criar um PR para corrigir a documentação.

**Comment by LorhanSohaky** [comment]
@diogoko , pode sim. Ficaremos felizes em revisar
