### ISSUE TITLE
Cep incorreto quando consultado na api

### ISSUE THREAD

**Issue by sostenesapollo** [BrasilAPI/BrasilAPI#578]
> Cep 7601-115 retorna que é de SP quando que é do MA

FYI: 
https://brasilapi.com.br/api/cep/v2/07601115
```
{
  "cep": "07601115",
  "state": "SP",
  "city": "Mairiporã",
  "neighborhood": "Olho D'Água",
  "street": "Rua Vinte e Quatro",
  "service": "correios",
  "location": {
    "type": "Point",
    "coordinates": {
      
    }
  }
}
```

**Comment by RodriAndreotti** [comment]
Olá, @sostenesapollo!
Tudo bem?
Acredito que esteja faltando algum caractere no seu CEP, consultando no site dos correios:
![image](https://github.com/BrasilAPI/BrasilAPI/assets/9449048/dd5489e2-114e-4498-b78a-4f4ee03a8ca0)

O Brasil é separado por faixas de cep, cada estado/região tem uma faixa própria, aqui vc encontra uma lista completa:
https://bring.com.br/suporte/?knowledgebase=faixas-de-cep-por-estado-e-regiao

A faixa de CEPs do Maranhão são estas:
Maranhão(MA) 65000-000 a 65999-999
