### ISSUE TITLE
Endpoint CNPJ fora do ar

### ISSUE THREAD

**Issue by eitchtee** [BrasilAPI/BrasilAPI#580]
O minha-receita parece estar fora do ar (https://github.com/cuducos/minha-receita/issues/204), e por consequência o endpoint do BrasilAPI também está, retornando erro 504

**Comment by Lucas-Angelo** [comment]
up

**Comment by 777-victor** [comment]
up

**Comment by Lucas-Angelo** [comment]
@filipedeschamps amigo, nos salve

**Comment by murilohns** [comment]
Precisamos esperar o provedor voltar. Vocês podem acompanhar o andamento por [essa issue](https://github.com/cuducos/minha-receita/issues/204)
