### ISSUE TITLE
API Consulta Cnpj

### ISSUE THREAD

**Issue by ct0rm4n** [BrasilAPI/BrasilAPI#581]
Bom dia! 
Nao encontrei canal de feedback report...
api cnpj esta retornando 504 retorno da cloudflare ou retorna
404 com json para um cnpj valido? 
Consulta sempre foi utilizada internamente e hoje esta com esse erro.
Nao possuem CI CD ambiente de teste?
http://brasilapi.com.br/api/cnpj/v1/{cnpj}

**Comment by J40Z1n** [comment]
Pelo que eu vi, a rota realiza a mesma chamada para a API do https://minhareceita.org que também está caindo.
Fuçando um pouco mais vi que a api do GOV https://h-apigateway.conectagov.estaleiro.serpro.gov.br/api-cnpj-empresa/v2/empresa/{CNPJempresa} ta dando status 403...

O problema deve ser na consulta CNPJ da serpro

**Comment by J40Z1n** [comment]
Aqui voltou a funcionar!

**Comment by ct0rm4n** [comment]
Recomendo ajustar calback conforme api da receita. Obrigado pelo feedback!
