### ISSUE TITLE
Hoje está dando erro parra qquer CEP

### ISSUE THREAD

**Issue by pcintra11** [BrasilAPI/BrasilAPI#598]
// https://brasilapi.com.br/api/cep/v2/04662002

{
  "message": "invalid json response body at https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&country=Brasil&state=SP&city=S%C3%A3o%20Paulo&street=Avenida%20Washington%20Lu%C3%ADs reason: Unexpected token < in JSON at position 0",
  "type": "invalid-json"
}

**Comment by murilohns** [comment]
@pcintra11 é um problema com o openstret map, pode usar a v1 por enquanto, por favor?

**Comment by luizsonego** [comment]
@murilohns  a v1 esta também com erros no retorno 
``` 
"name": "ServiceError",
"message": "A autenticacao de null falhou!",
"service": "correios"
````
Isso para retorno de todos os serviços "correios, viacep, widenet e correios-alt"

**Comment by lucianopf** [comment]
@luizsonego só pra garantir, esses erros na v1 que vc ta tendo são constantes pra diferentes ceps ou intermitentes? 👀

**Comment by pcintra11** [comment]
Aqui a V1 para cep está funcionando corretamente

**Comment by diogenesjup** [comment]
Problema ainda persiste na V2, indispensável para obtensão de coordenadas por exemplo

**Comment by diogenesjup** [comment]
A Open Street Maps está normal, tanto que eu a acesso normalmente usando https://nominatim.openstreetmap.org/search?format=json&country=Brasil&postalcode=69000000 indicando ser um problema na API da BrasilAPI mesmo

**Comment by luizsonego** [comment]
> @luizsonego só pra garantir, esses erros na v1 que vc ta tendo são constantes pra diferentes ceps ou intermitentes? 👀

Estive retestando e a v1 esse erro é quando esta com cep sem o hifén, se pesquisado no formato `00000-000` funciona, pode ter sido desatenção mas por usar a v2 como `INT` pode ter confundido.

Vale a pena colocar essa informação na documentação, pode ser que confunda outros igual me confundiu.
