### ISSUE TITLE
CEPs V1 - Erro - strict-origin-when-cross-origin

### ISSUE THREAD

**Issue by bcerquiare** [BrasilAPI/BrasilAPI#601]
Olá, primeiramente gostaria de agradecer ao trabalho de todos..
Gostaria também de um auxilio, estou utilizando a API de CEP v1 de vocês, porém ela parou de funcionar. Tentei contato pelo formulário mas não esta enviando.

Já gerei a minha chave e estou passando ela correntemente pelo meu header Authorization Bearer. Porém tenho recebido o seguinte erro: "strict-origin-when-cross-origin".

Vocês tem alguma informação sobre este problema ?
Mais uma vez, agradeço.

![image](https://github.com/BrasilAPI/BrasilAPI/assets/25101720/3ac01728-0f40-4c8d-b339-c656e0e5b722)

**Comment by murilohns** [comment]
@bcerquiare você confundiu, esse github é do BrasilApi, não do BrasilAberto 😬
