### ISSUE TITLE
Erro ao consultar CNPJ

### ISSUE THREAD

**Issue by brunopapait** [BrasilAPI/BrasilAPI#602]
Hoje está dando erros ao consultar CNPJs, 

![image](https://github.com/BrasilAPI/BrasilAPI/assets/53370576/329a7e99-4679-4902-a716-66e09ff374d8)

e quando acesso o link do minhareceita.org
https://minhareceita.org/50093374000177

ele ta retornando isso 
![image](https://github.com/BrasilAPI/BrasilAPI/assets/53370576/daf5803a-d0cd-4b4f-ad3d-8c9c868d62fd)

**Comment by cosmo-rodrigues** [comment]
Estou com o mesmo problema. Comentando para dar visibilidade!

**Comment by gilberto-maess** [comment]
Também estou com o mesmo problema. 

Na verdade, eu vi que a api consome de uma fonte de terceiro, o Minha Receita (https://minhareceita.org/) que está fora.
O Minha Receita pega os dados do portal dados.gov.br.
Eu comecei a baixar localmente o projeto para levantar uma nova api. Mas demora um pouco. São muitos gigas de arquivos.
Um outro ponto é que o Minha Receita usa o postgres pra fazer uma estrutura chave valor. Seria melhor empregado no redis ou até no mongodb mesmo - em caso de aplicar mais filtros. Poderíamos aplicar um índice de FTS pra fazer pesquisa ampla de texto. Não seria como um elastic search ou apache solr, mas traria uma experiência boa e barata pra levantara api.
Eu não sei se consigo levantar hoje, pois estou com outras demandas. Mas assim que terminar aviso aqui. Vou liberar um outro link.

**Comment by gilberto-maess** [comment]
https://github.com/cuducos/minha-receita/issues/204

O datacenter que o Minha Receita usa está em manutenção.

**Comment by brunopapait** [comment]
Sim sim .. estao em manutenção

**Comment by edervinicius** [comment]
Eu também estou com problemas, alguém já tem alguma resposta?

**Comment by gilberto-maess** [comment]
https://github.com/cuducos/minha-receita/issues/204

@edervinicius , o datacenter do Minha Receita estava em manutenção. O datacenter já está disponível.
Agora o @cuducos está levantando a base agora. Leva algumas horas como ele mesmo disse.
É muito dado mesmo!

**Comment by murilowippel** [comment]
Olá pessoal.

Realizando uma consulta hoje, a API de CNPJ está inacessível e por coincidência (ou não) o https://minhareceita.org/ também.

**Comment by murilowippel** [comment]
> Olá pessoal.
> 
> Realizando uma consulta hoje, a API de CNPJ está inacessível e por coincidência (ou não) o https://minhareceita.org/ também.

Acompanhando por aqui: https://github.com/cuducos/minha-receita/issues/204

**Comment by RenatoBrunetti** [comment]
Aparentemente está completamente estável novamente. Todos os testes retornaram corretamente.
