### ISSUE TITLE
Erro ao consultar CEP Api V2, para qualquer endereço

### ISSUE THREAD

**Issue by lsnepomuceno** [BrasilAPI/BrasilAPI#604]
Consulta de referência:
https://brasilapi.com.br/api/cep/v2/29018210

![image](https://github.com/BrasilAPI/BrasilAPI/assets/14093492/026d5f6c-5d2b-4e9c-a34c-89c662647693)

Utilizo a V2 por conta da latitude e longitude.

A V1 está funcionando normalmente.

**Comment by diogenesjup** [comment]
Duplicado de https://github.com/BrasilAPI/BrasilAPI/issues/596

**Comment by ffoliveira** [comment]
Fiz o serviço BrasilApi rodar localmente e não está dando o erro na obtenção do endereço a partir do CEP na versão v2
Esta esta dando erro:
https://brasilapi.com.br/api/cep/v2/18085-090

Internamente faz requisição à :
https://nominatim.openstreetmap.org/search.php?q=18085-090&format=jsonv2

Fiz rodar aqui com docker :
http://localhost:8080/api/cep/v2/18086290

retornou
{
  "cep": "18086290",
  "state": "SP",
  "city": "Sorocaba",
  "neighborhood": "Jardim Ibiti do Paço",
  "street": "Rua Luis Carlos Bertim",
  "service": "correios-alt",
  "location": {
    "type": "Point",
    "coordinates": {
      "longitude": "-47.4504745",
      "latitude": "-23.4455239"
    }
  }
}

**Comment by btguilherme** [comment]
@ffoliveira 
Poderia disponibilizar o `Dockerfile` ou `docker-compose`, por favor?

**Comment by ffoliveira** [comment]
Dockerfile usado

FROM node:16.20.2-buster
RUN apt-get update && apt-get install git
WORKDIR /app
RUN git clone https://github.com/BrasilAPI/BrasilAPI.git
WORKDIR /app/BrasilAPI
RUN npm install
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start"]

Não usei o docker compose, apenas construi a imagem e mapeei a porta 3000 para fora usando o Docker Desktop. e acessei essa porta como 8080

**Comment by btguilherme** [comment]
Muito obrigado, @ffoliveira

**Comment by alijuniorbr** [comment]
Recebo o mesmo erro, porém o estranho e que a ViaCep esta funcionando normalmente como verificado acessando [em formato JSON](https://viacep.com.br/ws/04513010/json) ou [em formato XML](https://viacep.com.br/ws/04513010/xml)

**Comment by juniorsantanamarcelo** [comment]
alguma novidade?

**Comment by LorhanSohaky** [comment]
Olá pessoal, estamos trabalhando nisso. O problema é que nosso serviço funciona como um proxy para outros provedores e estamos passando por DDOS e por conta disso estamos sendo bloqueados / passando por essa instabilidade.

**Comment by cauefajoli** [comment]
@LorhanSohaky alguma novidade?

**Comment by RodriAndreotti** [comment]
> @LorhanSohaky alguma novidade?

Subimos um provedor adicional de CEPs para resolver o problema, se puder nos reportar se o problema continua ocorrendo

**Comment by lsnepomuceno** [comment]
> > @LorhanSohaky alguma novidade?
> 
> Subimos um provedor adicional de CEPs para resolver o problema, se puder nos reportar se o problema continua ocorrendo

O V1 se mantem em funcionamento, porém o V2 ainda está com problema.

V1
![image](https://github.com/BrasilAPI/BrasilAPI/assets/14093492/1999ee1a-d77a-45db-8afe-1675dc32a71f)

V2
![image](https://github.com/BrasilAPI/BrasilAPI/assets/14093492/86ce326a-36e3-49e2-b4eb-33731a57c394)

**Comment by RenatoBrunetti** [comment]
O interessante é que ele retorna esse erro, mas a URL que está no erro contém o resultado do CEP.
https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&country=Brasil&state=ES&city=Vit%C3%B3ria&street=Rua%20Vasco%20Coutinho

**Comment by RenatoBrunetti** [comment]
Será que o erro pode estar relacionado ao fato da resposta ser um Array nesse caso?
