### ISSUE TITLE
API CNPJ retornando 404 para qualquer CNPJ

### ISSUE THREAD

**Issue by matheusrizzati** [BrasilAPI/BrasilAPI#605]
![image](https://github.com/BrasilAPI/BrasilAPI/assets/50409656/beb27625-e2ce-4b8f-999f-2134d0638324)

**Comment by lucasvini382** [comment]
Vi que esse é um erro da API minha-receita que está retornando 404. Abri uma issue por lá https://github.com/cuducos/minha-receita/issues/212

**Comment by matheusrizzati** [comment]
Valeu, @lucasvini382

**Comment by matheusrizzati** [comment]
Voltou a acontecer. Provavelmente acontece em alguma das apis usadas
