### ISSUE TITLE
Erro ao consultar CEP Api V1, para qualquer endereço

### ISSUE THREAD

**Issue by izidorio** [BrasilAPI/BrasilAPI#606]
https://brasilapi.com.br/api/cep/v1
```json
{
"message":"Todos os serviços de CEP retornaram erro.",
"type":"service_error",
"name":"CepPromiseError",
"errors":[
{
"name":"ServiceError",
"message":"A autenticacao de null falhou!",
"service":"correios"
},
{
"name":"ServiceError",
"message":"Erro ao se conectar com o serviço ViaCEP.",
"service":"viacep"
},
{
"name":"ServiceError",
"message":"Erro ao se conectar com o serviço WideNet.",
"service":"widenet"
},
{
"name":"ServiceError",
"message":"Erro ao se conectar com o serviço dos Correios Alt.",
"service":"correios-alt"
}
]
}
```

**Comment by alijuniorbr** [comment]
Recebo o mesmo erro, porém o estranho e que a ViaCep esta funcionando normalmente como verificado acessando [](https://viacep.com.br/ws/04513010/json) ou [](https://viacep.com.br/ws/04513010/xml)

**Comment by oproprioleonardo** [comment]
Estou tendo o mesmo problema... Ao testar na minha máquina local funciona, mas quando subo para o servidor estou recebendo este erro.

**Comment by LorhanSohaky** [comment]
Olá pessoal, estamos trabalhando nisso. O problema é que nosso serviço funciona como um proxy para outros provedores e estamos passando por DDOS e por conta disso estamos sendo bloqueados / passando por essa instabilidade.

**Comment by LorhanSohaky** [comment]
Pode nos dizer se melhorou?

**Comment by RenatoBrunetti** [comment]
> Pode nos dizer se melhorou?

Eu diria que sim, todos os testes que fiz com CEPs diferentes e de regiões diferentes funcionaram e todos eles com tempo resposta de aproximadamente 340ms.
![Screenshot 2024-05-14 at 16 04 15](https://github.com/BrasilAPI/BrasilAPI/assets/10968835/6ae9b716-9af7-4f5c-9771-fc9e1100642b)
