### ISSUE TITLE
Lista de municipios de Santa Catarina retornando lista com dados errados

### ISSUE THREAD

**Issue by ricardodalarme** [BrasilAPI/BrasilAPI#616]
## Descrição

Ao fazer a busca pelos municipios de Santa Catarina usando o provider wikipedia, a API retorna o nome de todas as cidades como `ORD`.

- https://brasilapi.com.br/api/ibge/municipios/v1/sc?providers=wikipedia

**Comment by kaiquevieirasoares** [comment]
### Resposta
o end-point da requisição está errado, o providers=wikipedia é desnecessário.
Tente : 
- https://brasilapi.com.br/api/ibge/municipios/v1/sc

**Comment by ricardodalarme** [comment]
Não está errado. Conforme a própria documentação mostra, é possível definir o provider Wikipedia para fazer a busca:

- https://brasilapi.com.br/docs#tag/IBGE/paths/~1ibge~1municipios~1v1~1{siglaUF}?providers=dados-abertos-br,gov,wikipedia/get

Portanto, se está na documentação e os dados estão vindo errados, então sãos dados que estão errados e não a chamada.

Olhando o código, ele só faz um parse da página da wikipedia, então talvez seja necessário ajustar no próprio Wikipedia ou então fazer um tratamento específico para o estado de Santa Catarina.

- https://github.com/BrasilAPI/BrasilAPI/blob/main/services/ibge/wikipedia.js

**Comment by RodriAndreotti** [comment]
> Não está errado. Conforme a própria documentação mostra, é possível definir o provider Wikipedia para fazer a busca:
> 
>     * [https://brasilapi.com.br/docs#tag/IBGE/paths/~1ibge~1municipios~1v1~1{siglaUF}?providers=dados-abertos-br,gov,wikipedia/get](https://brasilapi.com.br/docs#tag/IBGE/paths/~1ibge~1municipios~1v1~1%7BsiglaUF%7D?providers=dados-abertos-br,gov,wikipedia/get)
> 
> 
> Portanto, se está na documentação e os dados estão vindo errados, então sãos dados que estão errados e não a chamada.
> 
> Olhando o código, ele só faz um parse da página da wikipedia, então talvez seja necessário ajustar no próprio Wikipedia ou então fazer um tratamento específico para o estado de Santa Catarina.
> 
>     * https://github.com/BrasilAPI/BrasilAPI/blob/main/services/ibge/wikipedia.js

Fala, @ricardodalarme !

beleza?
O provider wikipedia usa um scrap na página para tentar carregar os dados da tabela que tem lá, porém pode acontecer de alguém mudar algo na página da wikipedia e quebrar o parser e ele não trazer nada ou trazer informação errada, pode ser essa a causa do problema.
Como não temos controle sobre as alterações da Wikipedia, foi criado esse parâmetro providers,
Basicamente, se ele está batendo na wikipedia e a wikipedia é a primeira que responde, pode ser esse o motivo, eu tentaria deixar todos os providers exceto a wikipedia (eu mesmo já tive esse problema com outro estado... rs)
