### ISSUE TITLE
Como faço para participar dos projetos?

### ISSUE THREAD

**Issue by Drijust** [BrasilAPI/BrasilAPI#627]

**Comment by RodriAndreotti** [comment]
Buenas, brother!
Tudo bem?

Bem vindo.
Você pode escolher alguma coisa que vc ache legal ter no projeto desenvolver e fazer o PR.
Nas issues e discussions tem algumas coisas que outras pessoas sugeriram, se quiser alguma ideia de por onde começar.

Aqui tem um guia de por onde começar e como fazer as contribuições:
https://github.com/BrasilAPI/BrasilAPI/blob/main/CONTRIBUTING.md

Apesar de não ter sido mergeado ainda (talvez ajustemos algo ainda) temos um pontapé inicial de boas práticas aqui:
https://github.com/BrasilAPI/BrasilAPI/blob/87409a35e9a326fc4ece06c2eef07555e8c445c8/GOOD_PRACTICES.md

**Comment by Drijust** [comment]
Blz mano !!! Estou no celular em casa eu vejo como está  o projeto eu sou estudante iniciante desenvolvedor Fullstake html css javascript  react na devclub .

**Comment by Drijust** [comment]
Vocês tem grupos de watzap?

**Comment by RodriAndreotti** [comment]
TOP!
Qualquer colaboração com o projeto é sempre bem vinda!
