### ISSUE TITLE
Error no Webpack 5

### ISSUE THREAD

**Issue by adeirjunior** [BrasilAPI/BrasilAPI#630]
Não estou conseguindo testar minhas alterações no código pois estou recebendo erros no webpack5.

Ao clonar o repositório, instalar as bibliotecas, executar o comando ``npm i`` e o comando ``npm run dev`` eu recebo o seguinte erro:

![image](https://github.com/user-attachments/assets/e58359a0-1f70-4501-b076-dc6b1e5af6c4)

Tenho a versão 20 do Node em minha máquina caso isto ajude.

**Comment by RodriAndreotti** [comment]
Atualmente o projeto roda em node 16, temos planos para fazer o upgrade da versão, mas o PR disso ainda não subiu.

**Comment by caiolombello** [comment]
> Atualmente, o projeto está rodando com Node.js 16, e já temos planos para fazer o upgrade da versão, embora o PR ainda não tenha sido aberto.

Uma solução para facilitar o desenvolvimento, especialmente para colaboradores que estão usando versões diferentes ou têm dificuldade em alternar entre elas, seria o uso de um **Dockerfile** (ao menos para o ambiente de desenvolvimento). Vi outras issues mencionando essa possibilidade, mas não acompanhei os resultados. De qualquer forma, um Dockerfile básico para isso poderia ser o seguinte:

```Dockerfile
FROM node:16

WORKDIR /app

COPY package*.json ./

RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]
```

Para buildar e rodar o container:

```
docker build -t brasilapi-dev .
docker run -p 3000:3000 -v $(pwd):/app -v /app/node_modules brasilapi-dev
```

Mesmo rodando em um container, essa configuração permite **live reloading** conforme as alterações são feitas no host. Isso pode simplificar bastante a vida dos devs que estão com versões diferentes do Node.js instaladas localmente.

**Comment by adeirjunior** [comment]
> > Atualmente, o projeto está rodando com Node.js 16, e já temos planos para fazer o upgrade da versão, embora o PR ainda não tenha sido aberto.
> 
> Uma solução para facilitar o desenvolvimento, especialmente para colaboradores que estão usando versões diferentes ou têm dificuldade em alternar entre elas, seria o uso de um **Dockerfile** (ao menos para o ambiente de desenvolvimento). Vi outras issues mencionando essa possibilidade, mas não acompanhei os resultados. De qualquer forma, um Dockerfile básico para isso poderia ser o seguinte:
> 
> ```Dockerfile
> FROM node:16
> 
> WORKDIR /app
> 
> COPY package*.json ./
> 
> RUN npm install
> 
> EXPOSE 3000
> 
> CMD ["npm", "run", "dev"]
> ```
> 
> Para buildar e rodar o container:
> 
> ```
> docker build -t brasilapi-dev .
> docker run -p 3000:3000 -v $(pwd):/app -v /app/node_modules brasilapi-dev
> ```
> 
> Mesmo rodando em um container, essa configuração permite **live reloading** conforme as alterações são feitas no host. Isso pode simplificar bastante a vida dos devs que estão com versões diferentes do Node.js instaladas localmente.

Eu pensei nisso, mas no caso acredito que seria bom incluir o Dockerfile pronto no repositório já

**Comment by caiolombello** [comment]
> > > Atualmente, o projeto está rodando com Node.js 16, e já temos planos para fazer o upgrade da versão, embora o PR ainda não tenha sido aberto.
> > 
> > 
> > Uma solução para facilitar o desenvolvimento, especialmente para colaboradores que estão usando versões diferentes ou têm dificuldade em alternar entre elas, seria o uso de um **Dockerfile** (ao menos para o ambiente de desenvolvimento). Vi outras issues mencionando essa possibilidade, mas não acompanhei os resultados. De qualquer forma, um Dockerfile básico para isso poderia ser o seguinte:
> > ```dockerfile
> > FROM node:16
> > 
> > WORKDIR /app
> > 
> > COPY package*.json ./
> > 
> > RUN npm install
> > 
> > EXPOSE 3000
> > 
> > CMD ["npm", "run", "dev"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Para buildar e rodar o container:
> > ```
> > docker build -t brasilapi-dev .
> > docker run -p 3000:3000 -v $(pwd):/app -v /app/node_modules brasilapi-dev
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Mesmo rodando em um container, essa configuração permite **live reloading** conforme as alterações são feitas no host. Isso pode simplificar bastante a vida dos devs que estão com versões diferentes do Node.js instaladas localmente.
> 
> Eu pensei nisso, mas no caso acredito que seria bom incluir o Dockerfile pronto no repositório já.
> 
> No momento a solução que encontrei foi usar o [nvm-windows](https://github.com/coreybutler/nvm-windows)

Sim, concordo, tava vendo de colocar aqui mas já tem alguns PRs sobre isso e confesso que estou perdido o pq de não ter sido adicionado

**Comment by adeirjunior** [comment]
Parece estarem meio travados os pull requests porque o Github Actions do projeto está desatualizado, e também tem alguns outros testes que não estão funcionando, aí os pull requests não estão mais sendo aceitos de forma automática. Estou tentando arrumar isso, porque parece que não tem gente com tempo pra ficar analisando todos os pulls.

**Comment by adeirjunior** [comment]
Acredito que o erro tenha sido consertado
