### ISSUE TITLE
CEP v1 e V2 erro relacionado ao CORS

### ISSUE THREAD

**Issue by DanielBASouza** [BrasilAPI/BrasilAPI#634]
Recebi alguns relatos de usuários que não estavam conseguindo puxar as informações utilizando o CEP, verifiquei e estou tendo problemas relacionados a CORS

**Comment by felipejuzo02** [comment]
up

**Comment by eliasassuncao** [comment]
up

mesmo problema aqui:
https://github.com/BrasilAPI/BrasilAPI/issues/635

**Comment by murilohns** [comment]
Fechando por duplicata, vamos resolver no #635

**Comment by LorhanSohaky** [comment]
@DanielBASouza , consegue disponibilizar o curl?
