### ISSUE TITLE
Problemas ao bater o OPTIONS (BUG)

### ISSUE THREAD

**Issue by eliasassuncao** [BrasilAPI/BrasilAPI#635]
O navegador faz a requisição OPTIONS antes do GET, e essas requisições dos options está sempre retornando 404, fazendo com que não prossiga para de fato fazer a requisição GET. Este problema começou repentinamente, antes estava usando as APIs normalmente. 

Print de exemplo através do Postman:
Requisição com OPTIONS:
![image](https://github.com/user-attachments/assets/b6ded771-c239-4d6c-af9f-7b81fcc43bea)

Requisição com GET:
![image](https://github.com/user-attachments/assets/105c555c-1d6e-4fc0-bd16-1c91adc7a5fd)

**Comment by DanielBASouza** [comment]
up

**Comment by DanielBASouza** [comment]
up

**Comment by murilohns** [comment]
Fizemos rollback da última versão @DanielBASouza @felipejuzo02 @eliasassuncao, podem validar, por favor?

**Comment by DanielBASouza** [comment]
Aparentemente tudo funcionando normalmente, fiz algumas requisições e deu tudo certo nos retornos.

**Comment by eliasassuncao** [comment]
voltou! obrigado.

**Comment by LorhanSohaky** [comment]
@eliasassuncao , consegue disponibilizar o curl?
