### ISSUE TITLE
Endpoint de dados climáticos

### ISSUE THREAD

**Issue by Davidson-Souza** [BrasilAPI/BrasilAPI#66]
Fala, turma! Tudo certo?
Já que a proposta é ser uma aplicação que condensa vários endpoint úteis em uma coisa só, acredito que um endpoint para buscar previsão do tempo seja algo razoável de ser pensado.
Aqui o exemplo de uma API bacana para buscar por esse tipo de dado: [HGBrasil](https://hgbrasil.com/status/weather)

**Comment by Nikolassantos** [comment]
> Fala, turma! Tudo certo?
> Já que a proposta é ser uma aplicação que condensa vários endpoint úteis em uma coisa só, acredito que um endpoint para buscar previsão do tempo seja algo razoável de ser pensado.
> Aqui o exemplo de uma API bacana para buscar por esse tipo de dado: [HGBrasil](https://hgbrasil.com/status/weather)

Achei muito boa essa API mencionada , acho que seria valido emplementarmos.

**Comment by gabrielbahniuk** [comment]
@Davidson-Souza @Nikolassantos voces ja chegaram a implementar algo? Gostaria de participar também :-)

Eu vi que essa API tem a parte financeira também: https://console.hgbrasil.com/documentation/finance

Talvez seja válido analisar se ja da pra fazer tanto a parte climática quanto a parte da BOVESPA (esta última em outra issue)
