### ISSUE TITLE
APIs do IBGE

### ISSUE THREAD

**Issue by frontendwizard** [BrasilAPI/BrasilAPI#67]
Em particular as APIs de malha geográfica e de localidades são úteis para cria gráficos e mapas sobre o brasil. A api de nomes também pode ser interessante.

https://servicodados.ibge.gov.br/api/docs

O que vocês acham?

**Comment by pereira299** [comment]
@thefrontendwizard acho bastante interessante as malhas geográficas do IBGE, contudo por enquanto eles só possuem malhas para regiões e estados. Por outro lado, se não me engano, no Wikipedia Images há SVGs dos estados, subdividido em mesorregião, microrregião e municípios.

**Comment by thefrontendwizard** [comment]
Dito isto, a coleção da wikipedia é bem impressionante e vai um pouco além. Só que talvez sirva a diferentes propósitos. Meu maior interesse nas apis do IBGE são os topojson que posso usar para renderizar os mapas criar visualizações usando a geografia do brasil, o que não seria simples nem trivial fazer com SVGs.
