### ISSUE TITLE
Busca de feriados nacionais

### ISSUE THREAD

**Issue by marcosvidolin** [BrasilAPI/BrasilAPI#68]
Fala pessoal,
Belezinha?

Seria legal ter no BrasilAPI um endpoint para obter informações de feriados de forma padão.
Pensando em algumas features com base em algo que já precisei desenvolver.

- Feriados por região (municipio, estado, etc)
- Quais os feriados endro de um intervalo de datas.
- O feriado é nacional?
- Facultativo?

Uma sugestão de campos de forma macro:

- **nome**: nome do feriado
- **data**: a data do feriado
- **descricao**: descrição prévia contextualizando o feriado
- **tipo**: se o feriado é nacional, estadual, ...
- **regiao**: qual a região em que o feriado se aplica

Na época usei como base essa API do [calendario](http://www.calendario.com.br/api_feriados_municipais_estaduais_nacionais.php) que por sinal, me ajudou bastante.

Parabens pela iniciativa pessoal.

**Comment by lukesamk** [comment]
Acho pertinente. Embora a ideia original seja ter uma API para CEPs, acredito que feriados também seja relevante!

**Comment by giovannicruz97** [comment]
Olá, estou chegando por aqui agora.

Em um país com tantos feriados como o Brasil, acho muito legal ter um endpoint que vc possa pesquisar por exemplo um CEP e saber quais são os feriados, pontos facultativos etc. 

Sobre essa API @marcosvidolin será que ela possui uma atualização rápida? Pergunto isso, pois imagino que nesse tempo de quarentena, em SP, por exemplo, tivemos feriados adiantados.

**Comment by marcosvidolin** [comment]
@giovannicruz97 teria que ser flexível o suficiente para possibilitar esse tipo de manutenção, já que um feriado pode sofrer alterações, ainda mais com isso que estamos passando. 😉✌️

**Comment by giovannicruz97** [comment]
> @giovannicruz97 teria que ser flexível o suficiente para possibilitar esse tipo de manutenção, já que um feriado pode sofrer alterações, ainda mais com isso que estamos passando. 😉✌️

É, eu acho que do nosso lado como consumidor da API não teria muito o que fazer a não ser esperar que a API do Calendário seja atualizada constantemente...

**Comment by jowpurcinelli** [comment]
> É, eu acho que do nosso lado como consumidor da API não teria muito o que fazer a não ser esperar que a API do Calendário seja atualizada constantemente...

Atualizar constantemente usando **automaziação**? hmmm...

**Comment by giovannicruz97** [comment]
> > É, eu acho que do nosso lado como consumidor da API não teria muito o que fazer a não ser esperar que a API do Calendário seja atualizada constantemente...
> 
> Atualizar constantemente usando **automaziação**? hmmm...

Como isso resolveria o fato do pessoal do Calendário manter ou não a API atualizada para nós (clientes) consumirmos os dados de maneira correta? Talvez ter uma fonte alternativa ou uma fonte que "corrija" algumas datas, mesmo que de forma manual e pontual?

**Comment by fmpierami** [comment]
Os feriados são divulgados nos diários oficiais da união, estados e municípios. Seria o caso de implementar a leitura das publicações, identificar os decretos, extrair os dados e disponibiliza-los. É uma quantidade de trabalho considerável.

**Comment by giovannicruz97** [comment]
> Os feriados são divulgados nos diários oficiais da união, estados e municípios. Seria o caso de implementar a leitura das publicações, identificar os decretos, extrair os dados e disponibiliza-los. É uma quantidade de trabalho considerável.

Sério? Vc sabe se existe alguma API ou dados do tipo raw (txt, xls, csv etc) que possa ser consumida?

**Comment by fmpierami** [comment]
Na realidade é uma salada de fruta. Por conta da lei de acesso à informação, todos são obrigados a disponibilizar digitalmente. A maioria dos órgãos fornecem um arquivo pdf e em alguns casos html puro ou xls. Às vezes publicações unificadas de vários municípios. Como disse, é muito trabalho para estruturar e ter uma boa margem de acerto. Talvez uma API que considere o uso de inteligência artificial.

**Comment by giovannicruz97** [comment]
> Na realidade é uma salada de fruta. Por conta da lei de acesso à informação, todos são obrigados a disponibilizar digitalmente. A maioria dos órgãos fornecem um arquivo pdf e em alguns casos html puro ou xls. Às vezes publicações unificadas de vários municípios. Como disse, é muito trabalho para estruturar e ter uma boa margem de acerto. Talvez uma API que considere o uso de inteligência artificial.

Tava dando uma lida no site do Calendário e parece que eles atualizam com bastante frequência os feriados, além de que eles deixam um email de contato para avisar que tem um feriado desatualizado. Eu seguiria com a Calendário API.

**Comment by marcosvidolin** [comment]
> Os feriados são divulgados nos diários oficiais da união, estados e municípios. Seria o caso de implementar a leitura das publicações, identificar os decretos, extrair os dados e disponibiliza-los. É uma quantidade de trabalho considerável.

Legal. Pode ser uma boa limitar o escopo de inicio. Fornecer apenas os feriados nacionais e estatuais, ou somente os feriados nacionais.

**Comment by pedrosancao** [comment]
> Legal. Pode ser uma boa limitar o escopo de inicio. Fornecer apenas os feriados nacionais e estatuais, ou somente os feriados nacionais.

Concordo, no PR #256 fiz a implementação dos feriados nacionais sem depender de serviços externos.

**Comment by murilohns** [comment]
fechado pelo #256
