### ISSUE TITLE
[Feature] API de consulta de instituições bancárias brasileiras

### ISSUE THREAD

**Issue by lucianopf** [BrasilAPI/BrasilAPI#78]
# Descrição

Seria interessante ter uma api que lista e descreve os dados das instituições financeiras no Brasil.
Isso é extremamente necessária para fintechs fazer operações financeiras e acredito que seria de grande ajuda pra várias pessoas! 😬 

Uma estrutura interessante que estava pensando era:
```json
{
  "ispb_code": "00000000",
  "name": "Banco do Brasil S.A.",
  "number_code": "001",
  "short_name": "BCO DO BRASIL S.A."
}
```

Assim como a rota de CEP os dados nessa base se alteram bem pouco e seria possível utilizar cache agressivo para manter tudo nas bordas da CDN por ao menos 24h.

**Comment by lucianopf** [comment]
Ótima ideia @matheusvellone , fica a vontade de atacar essa feature! 🤘 😍

**Comment by valdirmendesdev** [comment]
Alguém já está trabalhando nessa feature?!

**Comment by lucianopf** [comment]
Não sei confirmar mestre, @matheusvellone ta rolando algum desenvolvimento já? 😬

**Comment by matheusvellone** [comment]
@valdirmendesdev @lucianopf eu comecei, vou dar um gás amanhã e mando PR

**Comment by matheusvellone** [comment]
PR aberto @valdirmendesdev @lucianopf 👍

**Comment by danielramosbh74** [comment]
Olá pessoal,

Seguindo as orientações do @lucianopf quanto à padronização dos campos necessários e me baseando na tabela oficial do Banco Central que o @matheusvellone disponibilizou o link, converti esta tabela para Planilha Google, excluí algumas colunas, publiquei-a somente para visualização e criei um código inicial que pode ajudar ajudar no desenvolvimento desta API.

Só consegui gerar o array / JSON da tabela original via Console do Chrome, mas... já é alguma coisa para quem quiser dar continuidade e nos ajudar.

https://github.com/danielramosbh74/Brazilian-banks

**Comment by lucianopf** [comment]
@danielramosbh74 primeiramente muito massa vc se envolver na tarefa!! :clap: :rocket: 
Será que não é mais fácil só importar um arquivo JSON ou com uma consulta dinâmica como o @matheusvellone implementou no PR dele [aqui](https://github.com/filipedeschamps/BrasilAPI/pull/85/files?file-filters%5B%5D=.js#diff-3997e0d5c741bf6c3798352e94ad3623R3-R35)? :thinking:

**Comment by danielramosbh74** [comment]
> @danielramosbh74 primeiramente muito massa vc se envolver na tarefa!!  
> Será que não é mais fácil só importar um arquivo JSON ou com uma consulta dinâmica como o @matheusvellone implementou no PR dele [aqui](https://github.com/filipedeschamps/BrasilAPI/pull/85/files?file-filters%5B%5D=.js#diff-3997e0d5c741bf6c3798352e94ad3623R3-R35)?

Nossa @lucianopf ... fiquei até meio envergonhado da minha solução "gambiarra", rs... vocês já estão anos-luz na frente... 
Quanto mais eu estudo, mais vejo que tenho de estudar e me organizar mais... mas obrigado pelo toque e por me mostrar a solução do @matheusvellone (li rapidamente o código e vi que já está todo vinculado com o projeto, organizado, fácil de entender, usando boas práticas)...

Minha ideia inicial tinha sido só converter os dados a planilha em JSON do BC para vocês disponibilizarem o arquivo .JSON em algum banco de dados do projeto, mas observei no código do @matheusvellone que ele já importa o .CSV direto do site do BC e depois trabalha mais os dados remapeando os campos...

Enfim, **tentarei colaborar com algumas tarefas mais simples na medida do possível (é só vocês me dizerem e me orientarem)**, mas **preciso realmente focar mais na busca de trabalho remunerado (se souberem de alguma oportunidade que meu perfil se encaixe, por favor me avisem...)**, pois acho que mesmo tendo muito o que aprender já posso ser aproveitado de alguma forma com o que já sei até o momento.

Desculpe ter fugido um pouco do tema... mas com 46 anos tenho de me esforçar mais que a turma mais jovem para conseguir acompanhar tantas tecnologias, mesmo tendo tido o meu primeiro contato com computadores aos 15 anos, em 1989, com BASIC e COBOL, rs...

**Comment by lucianopf** [comment]
Mestre @danielramosbh74 seja bem vindo ao projeto BrasilAPI, sua ajuda é super bem vinda e sua ação de ir lá e criar uma proposta é ANIMAL!! :clap:  (como diria o @filipedeschamps delicinha! hehehe)

Vou tentar colocar um esforço essa semana pra categorizar as issues e definir o nivel técnico exigido que cada tarefa apresenta! :grimacing: 

De coração, muito obrigado por se envolver @danielramosbh74 !!

**Comment by webtingueta** [comment]
Fala pessoa!

Eu estava pesquisando e encontrei essa API do próprio BC

https://olinda.bcb.gov.br/olinda/servico/CCR/versao/v1/swagger-ui2

Ela é disponibilizada no Portal de Dados Abertos do Banco Central.

![Página do recurso: Lista das instituições financeiras autorizadas a operar no CCR ](]https://dadosabertos.bcb.gov.br/dataset/lista-das-instituies-financeiras-autorizadas-a-operar-no-ccr/resource/0412d6c6-9f4c-471c-a573-ef81bd77eec3**)

![Página: API - Documentação Swagger](https://dadosabertos.bcb.gov.br/dataset/lista-das-instituies-financeiras-autorizadas-a-operar-no-ccr/resource/0412d6c6-9f4c-471c-a573-ef81bd77eec3)

Se vocês acessarem o ![Portal de Dados Abertos do BC](https://dadosabertos.bcb.gov.br/) e pesquisarem por _lista de instituições_, vocês encontram essa API.

**Comment by michel1351** [comment]
Ok

**Comment by michel1351** [comment]
Teste
